// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: body_measurements.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getBodyMeasurementByDate = `-- name: GetBodyMeasurementByDate :one
SELECT id, client_id, local_id, date, weight_kg, waist_cm, hip_cm, abdomen_cm, thigh_cm, chest_cm, wrist_cm, recorded_by, created_at, updated_at FROM body_measurements WHERE client_id = $1 AND date = $2
`

type GetBodyMeasurementByDateParams struct {
	ClientID pgtype.UUID `json:"client_id"`
	Date     pgtype.Date `json:"date"`
}

func (q *Queries) GetBodyMeasurementByDate(ctx context.Context, arg GetBodyMeasurementByDateParams) (BodyMeasurement, error) {
	row := q.db.QueryRow(ctx, getBodyMeasurementByDate, arg.ClientID, arg.Date)
	var i BodyMeasurement
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.LocalID,
		&i.Date,
		&i.WeightKg,
		&i.WaistCm,
		&i.HipCm,
		&i.AbdomenCm,
		&i.ThighCm,
		&i.ChestCm,
		&i.WristCm,
		&i.RecordedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWeightHistory = `-- name: GetWeightHistory :many
SELECT date, weight_kg FROM body_measurements
WHERE client_id = $1 AND weight_kg IS NOT NULL
ORDER BY date ASC
`

type GetWeightHistoryRow struct {
	Date     pgtype.Date    `json:"date"`
	WeightKg pgtype.Numeric `json:"weight_kg"`
}

func (q *Queries) GetWeightHistory(ctx context.Context, clientID pgtype.UUID) ([]GetWeightHistoryRow, error) {
	rows, err := q.db.Query(ctx, getWeightHistory, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetWeightHistoryRow{}
	for rows.Next() {
		var i GetWeightHistoryRow
		if err := rows.Scan(&i.Date, &i.WeightKg); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBodyMeasurementsForNutritionist = `-- name: ListBodyMeasurementsForNutritionist :many
SELECT bm.id, bm.client_id, bm.local_id, bm.date, bm.weight_kg, bm.waist_cm, bm.hip_cm, bm.abdomen_cm, bm.thigh_cm, bm.chest_cm, bm.wrist_cm, bm.recorded_by, bm.created_at, bm.updated_at FROM body_measurements bm
JOIN users u ON u.id = bm.client_id AND u.nutritionist_id = $1
WHERE bm.client_id = $2 AND bm.date BETWEEN $3 AND $4
ORDER BY bm.date DESC
`

type ListBodyMeasurementsForNutritionistParams struct {
	NutritionistID pgtype.UUID `json:"nutritionist_id"`
	ClientID       pgtype.UUID `json:"client_id"`
	FromDate       pgtype.Date `json:"from_date"`
	ToDate         pgtype.Date `json:"to_date"`
}

func (q *Queries) ListBodyMeasurementsForNutritionist(ctx context.Context, arg ListBodyMeasurementsForNutritionistParams) ([]BodyMeasurement, error) {
	rows, err := q.db.Query(ctx, listBodyMeasurementsForNutritionist,
		arg.NutritionistID,
		arg.ClientID,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BodyMeasurement{}
	for rows.Next() {
		var i BodyMeasurement
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.LocalID,
			&i.Date,
			&i.WeightKg,
			&i.WaistCm,
			&i.HipCm,
			&i.AbdomenCm,
			&i.ThighCm,
			&i.ChestCm,
			&i.WristCm,
			&i.RecordedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBodyMeasurement = `-- name: UpsertBodyMeasurement :one
INSERT INTO body_measurements (id, client_id, local_id, date, weight_kg, waist_cm, hip_cm, abdomen_cm, thigh_cm, chest_cm, wrist_cm, recorded_by)
VALUES (gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (client_id, date) DO UPDATE SET
    weight_kg   = EXCLUDED.weight_kg,
    waist_cm    = EXCLUDED.waist_cm,
    hip_cm      = EXCLUDED.hip_cm,
    abdomen_cm  = EXCLUDED.abdomen_cm,
    thigh_cm    = EXCLUDED.thigh_cm,
    chest_cm    = EXCLUDED.chest_cm,
    wrist_cm    = EXCLUDED.wrist_cm,
    recorded_by = EXCLUDED.recorded_by,
    updated_at  = NOW()
RETURNING id, client_id, local_id, date, weight_kg, waist_cm, hip_cm, abdomen_cm, thigh_cm, chest_cm, wrist_cm, recorded_by, created_at, updated_at
`

type UpsertBodyMeasurementParams struct {
	ClientID   pgtype.UUID    `json:"client_id"`
	LocalID    pgtype.UUID    `json:"local_id"`
	Date       pgtype.Date    `json:"date"`
	WeightKg   pgtype.Numeric `json:"weight_kg"`
	WaistCm    pgtype.Numeric `json:"waist_cm"`
	HipCm      pgtype.Numeric `json:"hip_cm"`
	AbdomenCm  pgtype.Numeric `json:"abdomen_cm"`
	ThighCm    pgtype.Numeric `json:"thigh_cm"`
	ChestCm    pgtype.Numeric `json:"chest_cm"`
	WristCm    pgtype.Numeric `json:"wrist_cm"`
	RecordedBy pgtype.UUID    `json:"recorded_by"`
}

func (q *Queries) UpsertBodyMeasurement(ctx context.Context, arg UpsertBodyMeasurementParams) (BodyMeasurement, error) {
	row := q.db.QueryRow(ctx, upsertBodyMeasurement,
		arg.ClientID,
		arg.LocalID,
		arg.Date,
		arg.WeightKg,
		arg.WaistCm,
		arg.HipCm,
		arg.AbdomenCm,
		arg.ThighCm,
		arg.ChestCm,
		arg.WristCm,
		arg.RecordedBy,
	)
	var i BodyMeasurement
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.LocalID,
		&i.Date,
		&i.WeightKg,
		&i.WaistCm,
		&i.HipCm,
		&i.AbdomenCm,
		&i.ThighCm,
		&i.ChestCm,
		&i.WristCm,
		&i.RecordedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
