// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: diet_plans.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateDietPlan = `-- name: ActivateDietPlan :exec
UPDATE diet_plans
SET status = 'active', updated_at = NOW()
WHERE id = $1 AND nutritionist_id = $2
`

type ActivateDietPlanParams struct {
	ID             pgtype.UUID `json:"id"`
	NutritionistID pgtype.UUID `json:"nutritionist_id"`
}

func (q *Queries) ActivateDietPlan(ctx context.Context, arg ActivateDietPlanParams) error {
	_, err := q.db.Exec(ctx, activateDietPlan, arg.ID, arg.NutritionistID)
	return err
}

const archivePreviousActivePlan = `-- name: ArchivePreviousActivePlan :exec
UPDATE diet_plans
SET status = 'archived', updated_at = NOW()
WHERE client_id = $1 AND status = 'active' AND id != $2
`

type ArchivePreviousActivePlanParams struct {
	ClientID pgtype.UUID `json:"client_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) ArchivePreviousActivePlan(ctx context.Context, arg ArchivePreviousActivePlanParams) error {
	_, err := q.db.Exec(ctx, archivePreviousActivePlan, arg.ClientID, arg.ID)
	return err
}

const countClientPlans = `-- name: CountClientPlans :one
SELECT COUNT(*) FROM diet_plans
WHERE client_id = $1 AND nutritionist_id = $2
`

type CountClientPlansParams struct {
	ClientID       pgtype.UUID `json:"client_id"`
	NutritionistID pgtype.UUID `json:"nutritionist_id"`
}

func (q *Queries) CountClientPlans(ctx context.Context, arg CountClientPlansParams) (int64, error) {
	row := q.db.QueryRow(ctx, countClientPlans, arg.ClientID, arg.NutritionistID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMyPlans = `-- name: CountMyPlans :one
SELECT COUNT(*) FROM diet_plans
WHERE client_id = $1 AND status != 'draft'
`

func (q *Queries) CountMyPlans(ctx context.Context, clientID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMyPlans, clientID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDietPlan = `-- name: CreateDietPlan :one
INSERT INTO diet_plans (client_id, nutritionist_id, start_date, end_date, notes, daily_water_target_ml)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, client_id, nutritionist_id, start_date, end_date, notes, daily_water_target_ml, status, created_at, updated_at
`

type CreateDietPlanParams struct {
	ClientID           pgtype.UUID `json:"client_id"`
	NutritionistID     pgtype.UUID `json:"nutritionist_id"`
	StartDate          pgtype.Date `json:"start_date"`
	EndDate            pgtype.Date `json:"end_date"`
	Notes              pgtype.Text `json:"notes"`
	DailyWaterTargetMl pgtype.Int4 `json:"daily_water_target_ml"`
}

func (q *Queries) CreateDietPlan(ctx context.Context, arg CreateDietPlanParams) (DietPlan, error) {
	row := q.db.QueryRow(ctx, createDietPlan,
		arg.ClientID,
		arg.NutritionistID,
		arg.StartDate,
		arg.EndDate,
		arg.Notes,
		arg.DailyWaterTargetMl,
	)
	var i DietPlan
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.NutritionistID,
		&i.StartDate,
		&i.EndDate,
		&i.Notes,
		&i.DailyWaterTargetMl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDietPlan = `-- name: DeleteDietPlan :exec
DELETE FROM diet_plans
WHERE id = $1 AND nutritionist_id = $2 AND status = 'draft'
`

type DeleteDietPlanParams struct {
	ID             pgtype.UUID `json:"id"`
	NutritionistID pgtype.UUID `json:"nutritionist_id"`
}

func (q *Queries) DeleteDietPlan(ctx context.Context, arg DeleteDietPlanParams) error {
	_, err := q.db.Exec(ctx, deleteDietPlan, arg.ID, arg.NutritionistID)
	return err
}

const getActivePlanIDForClient = `-- name: GetActivePlanIDForClient :one
SELECT id FROM diet_plans
WHERE client_id = $1 AND status = 'active'
`

func (q *Queries) GetActivePlanIDForClient(ctx context.Context, clientID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getActivePlanIDForClient, clientID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getDietPlanByID = `-- name: GetDietPlanByID :one
SELECT id, client_id, nutritionist_id, start_date, end_date, notes, daily_water_target_ml, status, created_at, updated_at FROM diet_plans
WHERE id = $1 AND nutritionist_id = $2
`

type GetDietPlanByIDParams struct {
	ID             pgtype.UUID `json:"id"`
	NutritionistID pgtype.UUID `json:"nutritionist_id"`
}

func (q *Queries) GetDietPlanByID(ctx context.Context, arg GetDietPlanByIDParams) (DietPlan, error) {
	row := q.db.QueryRow(ctx, getDietPlanByID, arg.ID, arg.NutritionistID)
	var i DietPlan
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.NutritionistID,
		&i.StartDate,
		&i.EndDate,
		&i.Notes,
		&i.DailyWaterTargetMl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDietPlanByIDForClient = `-- name: GetDietPlanByIDForClient :one
SELECT id, client_id, nutritionist_id, start_date, end_date, notes, daily_water_target_ml, status, created_at, updated_at FROM diet_plans
WHERE id = $1 AND client_id = $2 AND status != 'draft'
`

type GetDietPlanByIDForClientParams struct {
	ID       pgtype.UUID `json:"id"`
	ClientID pgtype.UUID `json:"client_id"`
}

func (q *Queries) GetDietPlanByIDForClient(ctx context.Context, arg GetDietPlanByIDForClientParams) (DietPlan, error) {
	row := q.db.QueryRow(ctx, getDietPlanByIDForClient, arg.ID, arg.ClientID)
	var i DietPlan
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.NutritionistID,
		&i.StartDate,
		&i.EndDate,
		&i.Notes,
		&i.DailyWaterTargetMl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDietPlanStatus = `-- name: GetDietPlanStatus :one
SELECT status FROM diet_plans WHERE id = $1
`

func (q *Queries) GetDietPlanStatus(ctx context.Context, id pgtype.UUID) (DietPlanStatus, error) {
	row := q.db.QueryRow(ctx, getDietPlanStatus, id)
	var status DietPlanStatus
	err := row.Scan(&status)
	return status, err
}

const listClientPlans = `-- name: ListClientPlans :many
SELECT id, client_id, nutritionist_id, start_date, end_date, notes, daily_water_target_ml, status, created_at, updated_at FROM diet_plans
WHERE client_id = $1 AND nutritionist_id = $2
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListClientPlansParams struct {
	ClientID       pgtype.UUID `json:"client_id"`
	NutritionistID pgtype.UUID `json:"nutritionist_id"`
	OffsetVal      int32       `json:"offset_val"`
	LimitVal       int32       `json:"limit_val"`
}

func (q *Queries) ListClientPlans(ctx context.Context, arg ListClientPlansParams) ([]DietPlan, error) {
	rows, err := q.db.Query(ctx, listClientPlans,
		arg.ClientID,
		arg.NutritionistID,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DietPlan{}
	for rows.Next() {
		var i DietPlan
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.NutritionistID,
			&i.StartDate,
			&i.EndDate,
			&i.Notes,
			&i.DailyWaterTargetMl,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyPlans = `-- name: ListMyPlans :many
SELECT id, client_id, nutritionist_id, start_date, end_date, notes, daily_water_target_ml, status, created_at, updated_at FROM diet_plans
WHERE client_id = $1 AND status != 'draft'
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListMyPlansParams struct {
	ClientID  pgtype.UUID `json:"client_id"`
	OffsetVal int32       `json:"offset_val"`
	LimitVal  int32       `json:"limit_val"`
}

func (q *Queries) ListMyPlans(ctx context.Context, arg ListMyPlansParams) ([]DietPlan, error) {
	rows, err := q.db.Query(ctx, listMyPlans, arg.ClientID, arg.OffsetVal, arg.LimitVal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DietPlan{}
	for rows.Next() {
		var i DietPlan
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.NutritionistID,
			&i.StartDate,
			&i.EndDate,
			&i.Notes,
			&i.DailyWaterTargetMl,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDietPlanHeader = `-- name: UpdateDietPlanHeader :one
UPDATE diet_plans
SET start_date            = $3,
    end_date              = $4,
    notes                 = $5,
    daily_water_target_ml = $6,
    updated_at            = NOW()
WHERE id = $1 AND nutritionist_id = $2
RETURNING id, client_id, nutritionist_id, start_date, end_date, notes, daily_water_target_ml, status, created_at, updated_at
`

type UpdateDietPlanHeaderParams struct {
	ID                 pgtype.UUID `json:"id"`
	NutritionistID     pgtype.UUID `json:"nutritionist_id"`
	StartDate          pgtype.Date `json:"start_date"`
	EndDate            pgtype.Date `json:"end_date"`
	Notes              pgtype.Text `json:"notes"`
	DailyWaterTargetMl pgtype.Int4 `json:"daily_water_target_ml"`
}

func (q *Queries) UpdateDietPlanHeader(ctx context.Context, arg UpdateDietPlanHeaderParams) (DietPlan, error) {
	row := q.db.QueryRow(ctx, updateDietPlanHeader,
		arg.ID,
		arg.NutritionistID,
		arg.StartDate,
		arg.EndDate,
		arg.Notes,
		arg.DailyWaterTargetMl,
	)
	var i DietPlan
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.NutritionistID,
		&i.StartDate,
		&i.EndDate,
		&i.Notes,
		&i.DailyWaterTargetMl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
