// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: exercise_logs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExerciseLog = `-- name: CreateExerciseLog :one
INSERT INTO exercise_logs (id, client_id, local_id, date, exercise_name, duration_minutes, calories_burned, notes)
VALUES (gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (local_id) DO NOTHING
RETURNING id, client_id, local_id, date, exercise_name, duration_minutes, calories_burned, notes, created_at
`

type CreateExerciseLogParams struct {
	ClientID        pgtype.UUID `json:"client_id"`
	LocalID         pgtype.UUID `json:"local_id"`
	Date            pgtype.Date `json:"date"`
	ExerciseName    string      `json:"exercise_name"`
	DurationMinutes int32       `json:"duration_minutes"`
	CaloriesBurned  pgtype.Int4 `json:"calories_burned"`
	Notes           pgtype.Text `json:"notes"`
}

func (q *Queries) CreateExerciseLog(ctx context.Context, arg CreateExerciseLogParams) (ExerciseLog, error) {
	row := q.db.QueryRow(ctx, createExerciseLog,
		arg.ClientID,
		arg.LocalID,
		arg.Date,
		arg.ExerciseName,
		arg.DurationMinutes,
		arg.CaloriesBurned,
		arg.Notes,
	)
	var i ExerciseLog
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.LocalID,
		&i.Date,
		&i.ExerciseName,
		&i.DurationMinutes,
		&i.CaloriesBurned,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const getExerciseLogByLocalID = `-- name: GetExerciseLogByLocalID :one
SELECT id, client_id, local_id, date, exercise_name, duration_minutes, calories_burned, notes, created_at FROM exercise_logs WHERE local_id = $1 AND client_id = $2
`

type GetExerciseLogByLocalIDParams struct {
	LocalID  pgtype.UUID `json:"local_id"`
	ClientID pgtype.UUID `json:"client_id"`
}

func (q *Queries) GetExerciseLogByLocalID(ctx context.Context, arg GetExerciseLogByLocalIDParams) (ExerciseLog, error) {
	row := q.db.QueryRow(ctx, getExerciseLogByLocalID, arg.LocalID, arg.ClientID)
	var i ExerciseLog
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.LocalID,
		&i.Date,
		&i.ExerciseName,
		&i.DurationMinutes,
		&i.CaloriesBurned,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const listExerciseLogsByDate = `-- name: ListExerciseLogsByDate :many
SELECT id, client_id, local_id, date, exercise_name, duration_minutes, calories_burned, notes, created_at FROM exercise_logs WHERE client_id = $1 AND date = $2 ORDER BY created_at ASC
`

type ListExerciseLogsByDateParams struct {
	ClientID pgtype.UUID `json:"client_id"`
	Date     pgtype.Date `json:"date"`
}

func (q *Queries) ListExerciseLogsByDate(ctx context.Context, arg ListExerciseLogsByDateParams) ([]ExerciseLog, error) {
	rows, err := q.db.Query(ctx, listExerciseLogsByDate, arg.ClientID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExerciseLog{}
	for rows.Next() {
		var i ExerciseLog
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.LocalID,
			&i.Date,
			&i.ExerciseName,
			&i.DurationMinutes,
			&i.CaloriesBurned,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExerciseLogsForNutritionist = `-- name: ListExerciseLogsForNutritionist :many
SELECT el.id, el.client_id, el.local_id, el.date, el.exercise_name, el.duration_minutes, el.calories_burned, el.notes, el.created_at FROM exercise_logs el
JOIN users u ON u.id = el.client_id AND u.nutritionist_id = $1
WHERE el.client_id = $2 AND el.date BETWEEN $3 AND $4
ORDER BY el.date DESC, el.created_at DESC
`

type ListExerciseLogsForNutritionistParams struct {
	NutritionistID pgtype.UUID `json:"nutritionist_id"`
	ClientID       pgtype.UUID `json:"client_id"`
	FromDate       pgtype.Date `json:"from_date"`
	ToDate         pgtype.Date `json:"to_date"`
}

func (q *Queries) ListExerciseLogsForNutritionist(ctx context.Context, arg ListExerciseLogsForNutritionistParams) ([]ExerciseLog, error) {
	rows, err := q.db.Query(ctx, listExerciseLogsForNutritionist,
		arg.NutritionistID,
		arg.ClientID,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExerciseLog{}
	for rows.Next() {
		var i ExerciseLog
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.LocalID,
			&i.Date,
			&i.ExerciseName,
			&i.DurationMinutes,
			&i.CaloriesBurned,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
