// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: foods.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/ranjbar-dev/nutritrack/backend/internal/model"
)

const addFoodCategory = `-- name: AddFoodCategory :exec
INSERT INTO food_categories (food_id, category) VALUES ($1, $2::food_category) ON CONFLICT DO NOTHING
`

type AddFoodCategoryParams struct {
	FoodID  pgtype.UUID        `json:"food_id"`
	Column2 model.FoodCategory `json:"column_2"`
}

func (q *Queries) AddFoodCategory(ctx context.Context, arg AddFoodCategoryParams) error {
	_, err := q.db.Exec(ctx, addFoodCategory, arg.FoodID, arg.Column2)
	return err
}

const checkDuplicateFoodName = `-- name: CheckDuplicateFoodName :one
SELECT EXISTS(
  SELECT 1 FROM foods
  WHERE LOWER(normalize_persian(name)) = LOWER(normalize_persian($1))
    AND is_active = true
    AND id != COALESCE($2::uuid, '00000000-0000-0000-0000-000000000000'::uuid)
) AS is_duplicate
`

type CheckDuplicateFoodNameParams struct {
	NormalizePersian string      `json:"normalize_persian"`
	ExcludeID        pgtype.UUID `json:"exclude_id"`
}

func (q *Queries) CheckDuplicateFoodName(ctx context.Context, arg CheckDuplicateFoodNameParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkDuplicateFoodName, arg.NormalizePersian, arg.ExcludeID)
	var is_duplicate bool
	err := row.Scan(&is_duplicate)
	return is_duplicate, err
}

const countActiveFoods = `-- name: CountActiveFoods :one
SELECT COUNT(*) FROM foods WHERE is_active = true
`

func (q *Queries) CountActiveFoods(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveFoods)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFoods = `-- name: CountFoods :one
SELECT COUNT(*)
FROM foods f
WHERE f.is_active = COALESCE($1::boolean, true)
  AND ($2::text IS NULL
    OR f.name_normalized ILIKE '%' || LOWER(normalize_persian($2::text)) || '%')
  AND ($3::text IS NULL
    OR EXISTS (
      SELECT 1 FROM food_categories fc
      WHERE fc.food_id = f.id
        AND fc.category::text = $3::text
    ))
`

type CountFoodsParams struct {
	IsActive pgtype.Bool `json:"is_active"`
	Search   pgtype.Text `json:"search"`
	Category pgtype.Text `json:"category"`
}

func (q *Queries) CountFoods(ctx context.Context, arg CountFoodsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFoods, arg.IsActive, arg.Search, arg.Category)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFood = `-- name: CreateFood :one
INSERT INTO foods (
    name, name_normalized, description, calories, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg,
    measurement_unit, measurement_amount, created_by
) VALUES (
    $1, LOWER(normalize_persian($1)), $2, $3, $4, $5, $6, $7, $8, $9,
    $10, $11, $12
) RETURNING id, name, name_normalized, description, calories, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg, measurement_unit, measurement_amount, is_active, created_by, created_at, updated_at
`

type CreateFoodParams struct {
	Name              string              `json:"name"`
	Description       pgtype.Text         `json:"description"`
	Calories          pgtype.Numeric      `json:"calories"`
	ProteinG          pgtype.Numeric      `json:"protein_g"`
	CarbsG            pgtype.Numeric      `json:"carbs_g"`
	FatG              pgtype.Numeric      `json:"fat_g"`
	FiberG            pgtype.Numeric      `json:"fiber_g"`
	SugarG            pgtype.Numeric      `json:"sugar_g"`
	SodiumMg          pgtype.Numeric      `json:"sodium_mg"`
	MeasurementUnit   MeasurementUnitType `json:"measurement_unit"`
	MeasurementAmount pgtype.Numeric      `json:"measurement_amount"`
	CreatedBy         pgtype.UUID         `json:"created_by"`
}

func (q *Queries) CreateFood(ctx context.Context, arg CreateFoodParams) (Food, error) {
	row := q.db.QueryRow(ctx, createFood,
		arg.Name,
		arg.Description,
		arg.Calories,
		arg.ProteinG,
		arg.CarbsG,
		arg.FatG,
		arg.FiberG,
		arg.SugarG,
		arg.SodiumMg,
		arg.MeasurementUnit,
		arg.MeasurementAmount,
		arg.CreatedBy,
	)
	var i Food
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameNormalized,
		&i.Description,
		&i.Calories,
		&i.ProteinG,
		&i.CarbsG,
		&i.FatG,
		&i.FiberG,
		&i.SugarG,
		&i.SodiumMg,
		&i.MeasurementUnit,
		&i.MeasurementAmount,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFoodCategories = `-- name: DeleteFoodCategories :exec
DELETE FROM food_categories WHERE food_id = $1
`

func (q *Queries) DeleteFoodCategories(ctx context.Context, foodID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteFoodCategories, foodID)
	return err
}

const getFoodByID = `-- name: GetFoodByID :one
SELECT f.id, f.name, f.name_normalized, f.description, f.calories, f.protein_g, f.carbs_g, f.fat_g, f.fiber_g, f.sugar_g, f.sodium_mg, f.measurement_unit, f.measurement_amount, f.is_active, f.created_by, f.created_at, f.updated_at, u.full_name AS creator_name
FROM foods f
JOIN users u ON f.created_by = u.id
WHERE f.id = $1
`

type GetFoodByIDRow struct {
	ID                pgtype.UUID         `json:"id"`
	Name              string              `json:"name"`
	NameNormalized    string              `json:"name_normalized"`
	Description       pgtype.Text         `json:"description"`
	Calories          pgtype.Numeric      `json:"calories"`
	ProteinG          pgtype.Numeric      `json:"protein_g"`
	CarbsG            pgtype.Numeric      `json:"carbs_g"`
	FatG              pgtype.Numeric      `json:"fat_g"`
	FiberG            pgtype.Numeric      `json:"fiber_g"`
	SugarG            pgtype.Numeric      `json:"sugar_g"`
	SodiumMg          pgtype.Numeric      `json:"sodium_mg"`
	MeasurementUnit   MeasurementUnitType `json:"measurement_unit"`
	MeasurementAmount pgtype.Numeric      `json:"measurement_amount"`
	IsActive          bool                `json:"is_active"`
	CreatedBy         pgtype.UUID         `json:"created_by"`
	CreatedAt         pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz  `json:"updated_at"`
	CreatorName       string              `json:"creator_name"`
}

func (q *Queries) GetFoodByID(ctx context.Context, id pgtype.UUID) (GetFoodByIDRow, error) {
	row := q.db.QueryRow(ctx, getFoodByID, id)
	var i GetFoodByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameNormalized,
		&i.Description,
		&i.Calories,
		&i.ProteinG,
		&i.CarbsG,
		&i.FatG,
		&i.FiberG,
		&i.SugarG,
		&i.SodiumMg,
		&i.MeasurementUnit,
		&i.MeasurementAmount,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatorName,
	)
	return i, err
}

const getFoodCategories = `-- name: GetFoodCategories :many
SELECT category::text AS category FROM food_categories WHERE food_id = $1
`

func (q *Queries) GetFoodCategories(ctx context.Context, foodID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getFoodCategories, foodID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var category string
		if err := rows.Scan(&category); err != nil {
			return nil, err
		}
		items = append(items, category)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFoods = `-- name: ListFoods :many
SELECT f.id, f.name, f.name_normalized, f.description, f.calories, f.protein_g, f.carbs_g, f.fat_g, f.fiber_g, f.sugar_g, f.sodium_mg, f.measurement_unit, f.measurement_amount, f.is_active, f.created_by, f.created_at, f.updated_at, u.full_name AS creator_name
FROM foods f
JOIN users u ON f.created_by = u.id
WHERE f.is_active = COALESCE($1::boolean, true)
  AND ($2::text IS NULL
    OR f.name_normalized ILIKE '%' || LOWER(normalize_persian($2::text)) || '%')
  AND ($3::text IS NULL
    OR EXISTS (
      SELECT 1 FROM food_categories fc
      WHERE fc.food_id = f.id
        AND fc.category::text = $3::text
    ))
ORDER BY
  CASE WHEN $2::text IS NOT NULL
    THEN similarity(f.name_normalized, LOWER(normalize_persian($2::text)))
    ELSE 0 END DESC,
  f.created_at DESC
LIMIT $5::bigint
OFFSET $4::bigint
`

type ListFoodsParams struct {
	IsActive  pgtype.Bool `json:"is_active"`
	Search    pgtype.Text `json:"search"`
	Category  pgtype.Text `json:"category"`
	OffsetVal int64       `json:"offset_val"`
	LimitVal  int64       `json:"limit_val"`
}

type ListFoodsRow struct {
	ID                pgtype.UUID         `json:"id"`
	Name              string              `json:"name"`
	NameNormalized    string              `json:"name_normalized"`
	Description       pgtype.Text         `json:"description"`
	Calories          pgtype.Numeric      `json:"calories"`
	ProteinG          pgtype.Numeric      `json:"protein_g"`
	CarbsG            pgtype.Numeric      `json:"carbs_g"`
	FatG              pgtype.Numeric      `json:"fat_g"`
	FiberG            pgtype.Numeric      `json:"fiber_g"`
	SugarG            pgtype.Numeric      `json:"sugar_g"`
	SodiumMg          pgtype.Numeric      `json:"sodium_mg"`
	MeasurementUnit   MeasurementUnitType `json:"measurement_unit"`
	MeasurementAmount pgtype.Numeric      `json:"measurement_amount"`
	IsActive          bool                `json:"is_active"`
	CreatedBy         pgtype.UUID         `json:"created_by"`
	CreatedAt         pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz  `json:"updated_at"`
	CreatorName       string              `json:"creator_name"`
}

func (q *Queries) ListFoods(ctx context.Context, arg ListFoodsParams) ([]ListFoodsRow, error) {
	rows, err := q.db.Query(ctx, listFoods,
		arg.IsActive,
		arg.Search,
		arg.Category,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFoodsRow{}
	for rows.Next() {
		var i ListFoodsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameNormalized,
			&i.Description,
			&i.Calories,
			&i.ProteinG,
			&i.CarbsG,
			&i.FatG,
			&i.FiberG,
			&i.SugarG,
			&i.SodiumMg,
			&i.MeasurementUnit,
			&i.MeasurementAmount,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteFood = `-- name: SoftDeleteFood :exec
UPDATE foods SET is_active = false, updated_at = NOW() WHERE id = $1
`

func (q *Queries) SoftDeleteFood(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteFood, id)
	return err
}

const softDeleteFoodByOwner = `-- name: SoftDeleteFoodByOwner :exec
UPDATE foods SET is_active = false, updated_at = NOW() WHERE id = $1 AND created_by = $2
`

type SoftDeleteFoodByOwnerParams struct {
	ID        pgtype.UUID `json:"id"`
	CreatedBy pgtype.UUID `json:"created_by"`
}

func (q *Queries) SoftDeleteFoodByOwner(ctx context.Context, arg SoftDeleteFoodByOwnerParams) error {
	_, err := q.db.Exec(ctx, softDeleteFoodByOwner, arg.ID, arg.CreatedBy)
	return err
}

const updateFood = `-- name: UpdateFood :one
UPDATE foods
SET name = $2,
    name_normalized = LOWER(normalize_persian($2)),
    description = $3,
    calories = $4,
    protein_g = $5,
    carbs_g = $6,
    fat_g = $7,
    fiber_g = $8,
    sugar_g = $9,
    sodium_mg = $10,
    measurement_unit = $11,
    measurement_amount = $12,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, name_normalized, description, calories, protein_g, carbs_g, fat_g, fiber_g, sugar_g, sodium_mg, measurement_unit, measurement_amount, is_active, created_by, created_at, updated_at
`

type UpdateFoodParams struct {
	ID                pgtype.UUID         `json:"id"`
	Name              string              `json:"name"`
	Description       pgtype.Text         `json:"description"`
	Calories          pgtype.Numeric      `json:"calories"`
	ProteinG          pgtype.Numeric      `json:"protein_g"`
	CarbsG            pgtype.Numeric      `json:"carbs_g"`
	FatG              pgtype.Numeric      `json:"fat_g"`
	FiberG            pgtype.Numeric      `json:"fiber_g"`
	SugarG            pgtype.Numeric      `json:"sugar_g"`
	SodiumMg          pgtype.Numeric      `json:"sodium_mg"`
	MeasurementUnit   MeasurementUnitType `json:"measurement_unit"`
	MeasurementAmount pgtype.Numeric      `json:"measurement_amount"`
}

func (q *Queries) UpdateFood(ctx context.Context, arg UpdateFoodParams) (Food, error) {
	row := q.db.QueryRow(ctx, updateFood,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Calories,
		arg.ProteinG,
		arg.CarbsG,
		arg.FatG,
		arg.FiberG,
		arg.SugarG,
		arg.SodiumMg,
		arg.MeasurementUnit,
		arg.MeasurementAmount,
	)
	var i Food
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameNormalized,
		&i.Description,
		&i.Calories,
		&i.ProteinG,
		&i.CarbsG,
		&i.FatG,
		&i.FiberG,
		&i.SugarG,
		&i.SodiumMg,
		&i.MeasurementUnit,
		&i.MeasurementAmount,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
