// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: food_requests.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFoodRequest = `-- name: CreateFoodRequest :one
INSERT INTO food_requests (food_name, description, requested_by)
VALUES ($1, $2, $3)
RETURNING id, food_name, description, status, rejection_reason, requested_by, reviewed_by, created_at, updated_at
`

type CreateFoodRequestParams struct {
	FoodName    string      `json:"food_name"`
	Description pgtype.Text `json:"description"`
	RequestedBy pgtype.UUID `json:"requested_by"`
}

func (q *Queries) CreateFoodRequest(ctx context.Context, arg CreateFoodRequestParams) (FoodRequest, error) {
	row := q.db.QueryRow(ctx, createFoodRequest, arg.FoodName, arg.Description, arg.RequestedBy)
	var i FoodRequest
	err := row.Scan(
		&i.ID,
		&i.FoodName,
		&i.Description,
		&i.Status,
		&i.RejectionReason,
		&i.RequestedBy,
		&i.ReviewedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFoodRequestsByClient = `-- name: ListFoodRequestsByClient :many
SELECT id, food_name, description, status, rejection_reason, requested_by, reviewed_by, created_at, updated_at
FROM food_requests
WHERE requested_by = $1
ORDER BY created_at DESC
`

func (q *Queries) ListFoodRequestsByClient(ctx context.Context, requestedBy pgtype.UUID) ([]FoodRequest, error) {
	rows, err := q.db.Query(ctx, listFoodRequestsByClient, requestedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FoodRequest{}
	for rows.Next() {
		var i FoodRequest
		if err := rows.Scan(
			&i.ID,
			&i.FoodName,
			&i.Description,
			&i.Status,
			&i.RejectionReason,
			&i.RequestedBy,
			&i.ReviewedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingFoodRequestsForNutritionist = `-- name: ListPendingFoodRequestsForNutritionist :many
SELECT fr.id, fr.food_name, fr.description, fr.status, fr.rejection_reason, fr.requested_by, fr.reviewed_by, fr.created_at, fr.updated_at
FROM food_requests fr
JOIN users u ON u.id = fr.requested_by AND u.nutritionist_id = $1
WHERE fr.status = 'pending'
ORDER BY fr.created_at ASC
`

func (q *Queries) ListPendingFoodRequestsForNutritionist(ctx context.Context, nutritionistID pgtype.UUID) ([]FoodRequest, error) {
	rows, err := q.db.Query(ctx, listPendingFoodRequestsForNutritionist, nutritionistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FoodRequest{}
	for rows.Next() {
		var i FoodRequest
		if err := rows.Scan(
			&i.ID,
			&i.FoodName,
			&i.Description,
			&i.Status,
			&i.RejectionReason,
			&i.RequestedBy,
			&i.ReviewedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFoodRequestByID = `-- name: GetFoodRequestByID :one
SELECT id, food_name, description, status, rejection_reason, requested_by, reviewed_by, created_at, updated_at
FROM food_requests
WHERE id = $1
`

func (q *Queries) GetFoodRequestByID(ctx context.Context, id pgtype.UUID) (FoodRequest, error) {
	row := q.db.QueryRow(ctx, getFoodRequestByID, id)
	var i FoodRequest
	err := row.Scan(
		&i.ID,
		&i.FoodName,
		&i.Description,
		&i.Status,
		&i.RejectionReason,
		&i.RequestedBy,
		&i.ReviewedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const approveFoodRequest = `-- name: ApproveFoodRequest :one
UPDATE food_requests
SET status = 'approved', reviewed_by = $2, updated_at = NOW()
WHERE id = $1 AND status = 'pending'
RETURNING id, food_name, description, status, rejection_reason, requested_by, reviewed_by, created_at, updated_at
`

type ApproveFoodRequestParams struct {
	ID         pgtype.UUID `json:"id"`
	ReviewedBy pgtype.UUID `json:"reviewed_by"`
}

func (q *Queries) ApproveFoodRequest(ctx context.Context, arg ApproveFoodRequestParams) (FoodRequest, error) {
	row := q.db.QueryRow(ctx, approveFoodRequest, arg.ID, arg.ReviewedBy)
	var i FoodRequest
	err := row.Scan(
		&i.ID,
		&i.FoodName,
		&i.Description,
		&i.Status,
		&i.RejectionReason,
		&i.RequestedBy,
		&i.ReviewedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const rejectFoodRequest = `-- name: RejectFoodRequest :one
UPDATE food_requests
SET status = 'rejected', rejection_reason = $2, reviewed_by = $3, updated_at = NOW()
WHERE id = $1 AND status = 'pending'
RETURNING id, food_name, description, status, rejection_reason, requested_by, reviewed_by, created_at, updated_at
`

type RejectFoodRequestParams struct {
	ID              pgtype.UUID `json:"id"`
	RejectionReason pgtype.Text `json:"rejection_reason"`
	ReviewedBy      pgtype.UUID `json:"reviewed_by"`
}

func (q *Queries) RejectFoodRequest(ctx context.Context, arg RejectFoodRequestParams) (FoodRequest, error) {
	row := q.db.QueryRow(ctx, rejectFoodRequest, arg.ID, arg.RejectionReason, arg.ReviewedBy)
	var i FoodRequest
	err := row.Scan(
		&i.ID,
		&i.FoodName,
		&i.Description,
		&i.Status,
		&i.RejectionReason,
		&i.RequestedBy,
		&i.ReviewedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
