// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: meal_options.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMealOption = `-- name: CreateMealOption :one
INSERT INTO meal_options (meal_id, option_number, label)
VALUES ($1, $2, $3)
RETURNING id, meal_id, option_number, label, created_at
`

type CreateMealOptionParams struct {
	MealID       pgtype.UUID `json:"meal_id"`
	OptionNumber int16       `json:"option_number"`
	Label        pgtype.Text `json:"label"`
}

func (q *Queries) CreateMealOption(ctx context.Context, arg CreateMealOptionParams) (MealOption, error) {
	row := q.db.QueryRow(ctx, createMealOption, arg.MealID, arg.OptionNumber, arg.Label)
	var i MealOption
	err := row.Scan(
		&i.ID,
		&i.MealID,
		&i.OptionNumber,
		&i.Label,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMealOption = `-- name: DeleteMealOption :exec
DELETE FROM meal_options
WHERE id = $1 AND meal_id = $2
`

type DeleteMealOptionParams struct {
	ID     pgtype.UUID `json:"id"`
	MealID pgtype.UUID `json:"meal_id"`
}

func (q *Queries) DeleteMealOption(ctx context.Context, arg DeleteMealOptionParams) error {
	_, err := q.db.Exec(ctx, deleteMealOption, arg.ID, arg.MealID)
	return err
}

const getMealOptionByID = `-- name: GetMealOptionByID :one
SELECT id, meal_id, option_number, label, created_at FROM meal_options
WHERE id = $1 AND meal_id = $2
`

type GetMealOptionByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	MealID pgtype.UUID `json:"meal_id"`
}

func (q *Queries) GetMealOptionByID(ctx context.Context, arg GetMealOptionByIDParams) (MealOption, error) {
	row := q.db.QueryRow(ctx, getMealOptionByID, arg.ID, arg.MealID)
	var i MealOption
	err := row.Scan(
		&i.ID,
		&i.MealID,
		&i.OptionNumber,
		&i.Label,
		&i.CreatedAt,
	)
	return i, err
}

const getNextOptionNumber = `-- name: GetNextOptionNumber :one
SELECT COALESCE(MAX(option_number), 0) + 1 AS next_option_number
FROM meal_options
WHERE meal_id = $1
`

func (q *Queries) GetNextOptionNumber(ctx context.Context, mealID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getNextOptionNumber, mealID)
	var next_option_number int32
	err := row.Scan(&next_option_number)
	return next_option_number, err
}

const listMealOptions = `-- name: ListMealOptions :many
SELECT id, meal_id, option_number, label, created_at FROM meal_options
WHERE meal_id = $1
ORDER BY option_number ASC
`

func (q *Queries) ListMealOptions(ctx context.Context, mealID pgtype.UUID) ([]MealOption, error) {
	rows, err := q.db.Query(ctx, listMealOptions, mealID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MealOption{}
	for rows.Next() {
		var i MealOption
		if err := rows.Scan(
			&i.ID,
			&i.MealID,
			&i.OptionNumber,
			&i.Label,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
