// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: meal_option_items.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMealOptionItem = `-- name: CreateMealOptionItem :one
INSERT INTO meal_option_items (option_id, food_id, quantity, measurement_unit, notes)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, option_id, food_id, quantity, measurement_unit, notes, created_at
`

type CreateMealOptionItemParams struct {
	OptionID        pgtype.UUID         `json:"option_id"`
	FoodID          pgtype.UUID         `json:"food_id"`
	Quantity        pgtype.Numeric      `json:"quantity"`
	MeasurementUnit MeasurementUnitType `json:"measurement_unit"`
	Notes           pgtype.Text         `json:"notes"`
}

func (q *Queries) CreateMealOptionItem(ctx context.Context, arg CreateMealOptionItemParams) (MealOptionItem, error) {
	row := q.db.QueryRow(ctx, createMealOptionItem,
		arg.OptionID,
		arg.FoodID,
		arg.Quantity,
		arg.MeasurementUnit,
		arg.Notes,
	)
	var i MealOptionItem
	err := row.Scan(
		&i.ID,
		&i.OptionID,
		&i.FoodID,
		&i.Quantity,
		&i.MeasurementUnit,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMealOptionItem = `-- name: DeleteMealOptionItem :exec
DELETE FROM meal_option_items
WHERE id = $1 AND option_id = $2
`

type DeleteMealOptionItemParams struct {
	ID       pgtype.UUID `json:"id"`
	OptionID pgtype.UUID `json:"option_id"`
}

func (q *Queries) DeleteMealOptionItem(ctx context.Context, arg DeleteMealOptionItemParams) error {
	_, err := q.db.Exec(ctx, deleteMealOptionItem, arg.ID, arg.OptionID)
	return err
}

const getMealOptionItemByID = `-- name: GetMealOptionItemByID :one
SELECT id, option_id, food_id, quantity, measurement_unit, notes, created_at FROM meal_option_items
WHERE id = $1 AND option_id = $2
`

type GetMealOptionItemByIDParams struct {
	ID       pgtype.UUID `json:"id"`
	OptionID pgtype.UUID `json:"option_id"`
}

func (q *Queries) GetMealOptionItemByID(ctx context.Context, arg GetMealOptionItemByIDParams) (MealOptionItem, error) {
	row := q.db.QueryRow(ctx, getMealOptionItemByID, arg.ID, arg.OptionID)
	var i MealOptionItem
	err := row.Scan(
		&i.ID,
		&i.OptionID,
		&i.FoodID,
		&i.Quantity,
		&i.MeasurementUnit,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const updateMealOptionItem = `-- name: UpdateMealOptionItem :one
UPDATE meal_option_items
SET quantity         = $2,
    measurement_unit = $3,
    notes            = $4
WHERE id = $1
RETURNING id, option_id, food_id, quantity, measurement_unit, notes, created_at
`

type UpdateMealOptionItemParams struct {
	ID              pgtype.UUID         `json:"id"`
	Quantity        pgtype.Numeric      `json:"quantity"`
	MeasurementUnit MeasurementUnitType `json:"measurement_unit"`
	Notes           pgtype.Text         `json:"notes"`
}

func (q *Queries) UpdateMealOptionItem(ctx context.Context, arg UpdateMealOptionItemParams) (MealOptionItem, error) {
	row := q.db.QueryRow(ctx, updateMealOptionItem,
		arg.ID,
		arg.Quantity,
		arg.MeasurementUnit,
		arg.Notes,
	)
	var i MealOptionItem
	err := row.Scan(
		&i.ID,
		&i.OptionID,
		&i.FoodID,
		&i.Quantity,
		&i.MeasurementUnit,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}
