// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: meals.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMeal = `-- name: CreateMeal :one
INSERT INTO meals (day_id, title, scheduled_time, display_order)
VALUES ($1, $2, $3, $4)
RETURNING id, day_id, title, scheduled_time, display_order, created_at, updated_at
`

type CreateMealParams struct {
	DayID         pgtype.UUID `json:"day_id"`
	Title         string      `json:"title"`
	ScheduledTime pgtype.Time `json:"scheduled_time"`
	DisplayOrder  int32       `json:"display_order"`
}

func (q *Queries) CreateMeal(ctx context.Context, arg CreateMealParams) (Meal, error) {
	row := q.db.QueryRow(ctx, createMeal,
		arg.DayID,
		arg.Title,
		arg.ScheduledTime,
		arg.DisplayOrder,
	)
	var i Meal
	err := row.Scan(
		&i.ID,
		&i.DayID,
		&i.Title,
		&i.ScheduledTime,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMeal = `-- name: DeleteMeal :exec
DELETE FROM meals
WHERE id = $1 AND day_id = $2
`

type DeleteMealParams struct {
	ID    pgtype.UUID `json:"id"`
	DayID pgtype.UUID `json:"day_id"`
}

func (q *Queries) DeleteMeal(ctx context.Context, arg DeleteMealParams) error {
	_, err := q.db.Exec(ctx, deleteMeal, arg.ID, arg.DayID)
	return err
}

const getMealByID = `-- name: GetMealByID :one
SELECT id, day_id, title, scheduled_time, display_order, created_at, updated_at FROM meals
WHERE id = $1 AND day_id = $2
`

type GetMealByIDParams struct {
	ID    pgtype.UUID `json:"id"`
	DayID pgtype.UUID `json:"day_id"`
}

func (q *Queries) GetMealByID(ctx context.Context, arg GetMealByIDParams) (Meal, error) {
	row := q.db.QueryRow(ctx, getMealByID, arg.ID, arg.DayID)
	var i Meal
	err := row.Scan(
		&i.ID,
		&i.DayID,
		&i.Title,
		&i.ScheduledTime,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMeals = `-- name: ListMeals :many
SELECT id, day_id, title, scheduled_time, display_order, created_at, updated_at FROM meals
WHERE day_id = $1
ORDER BY display_order ASC, scheduled_time ASC
`

func (q *Queries) ListMeals(ctx context.Context, dayID pgtype.UUID) ([]Meal, error) {
	rows, err := q.db.Query(ctx, listMeals, dayID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Meal{}
	for rows.Next() {
		var i Meal
		if err := rows.Scan(
			&i.ID,
			&i.DayID,
			&i.Title,
			&i.ScheduledTime,
			&i.DisplayOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reorderMeal = `-- name: ReorderMeal :exec
UPDATE meals
SET display_order = $2
WHERE id = $1
`

type ReorderMealParams struct {
	ID           pgtype.UUID `json:"id"`
	DisplayOrder int32       `json:"display_order"`
}

func (q *Queries) ReorderMeal(ctx context.Context, arg ReorderMealParams) error {
	_, err := q.db.Exec(ctx, reorderMeal, arg.ID, arg.DisplayOrder)
	return err
}

const updateMeal = `-- name: UpdateMeal :one
UPDATE meals
SET title          = $2,
    scheduled_time = $3,
    display_order  = $4,
    updated_at     = NOW()
WHERE id = $1
RETURNING id, day_id, title, scheduled_time, display_order, created_at, updated_at
`

type UpdateMealParams struct {
	ID            pgtype.UUID `json:"id"`
	Title         string      `json:"title"`
	ScheduledTime pgtype.Time `json:"scheduled_time"`
	DisplayOrder  int32       `json:"display_order"`
}

func (q *Queries) UpdateMeal(ctx context.Context, arg UpdateMealParams) (Meal, error) {
	row := q.db.QueryRow(ctx, updateMeal,
		arg.ID,
		arg.Title,
		arg.ScheduledTime,
		arg.DisplayOrder,
	)
	var i Meal
	err := row.Scan(
		&i.ID,
		&i.DayID,
		&i.Title,
		&i.ScheduledTime,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
