// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: medication_logs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMedicationLog = `-- name: CreateMedicationLog :one
INSERT INTO medication_logs (id, client_id, local_id, date, prescribed_medication_id, medication_name, dosage, taken_at, notes, is_self_reported)
VALUES (gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (local_id) DO NOTHING
RETURNING id, client_id, local_id, date, prescribed_medication_id, medication_name, dosage, taken_at, notes, is_self_reported, created_at
`

type CreateMedicationLogParams struct {
	ClientID               pgtype.UUID `json:"client_id"`
	LocalID                pgtype.UUID `json:"local_id"`
	Date                   pgtype.Date `json:"date"`
	PrescribedMedicationID pgtype.UUID `json:"prescribed_medication_id"`
	MedicationName         string      `json:"medication_name"`
	Dosage                 pgtype.Text `json:"dosage"`
	TakenAt                pgtype.Time `json:"taken_at"`
	Notes                  pgtype.Text `json:"notes"`
	IsSelfReported         bool        `json:"is_self_reported"`
}

func (q *Queries) CreateMedicationLog(ctx context.Context, arg CreateMedicationLogParams) (MedicationLog, error) {
	row := q.db.QueryRow(ctx, createMedicationLog,
		arg.ClientID,
		arg.LocalID,
		arg.Date,
		arg.PrescribedMedicationID,
		arg.MedicationName,
		arg.Dosage,
		arg.TakenAt,
		arg.Notes,
		arg.IsSelfReported,
	)
	var i MedicationLog
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.LocalID,
		&i.Date,
		&i.PrescribedMedicationID,
		&i.MedicationName,
		&i.Dosage,
		&i.TakenAt,
		&i.Notes,
		&i.IsSelfReported,
		&i.CreatedAt,
	)
	return i, err
}

const getMedicationLogByLocalID = `-- name: GetMedicationLogByLocalID :one
SELECT id, client_id, local_id, date, prescribed_medication_id, medication_name, dosage, taken_at, notes, is_self_reported, created_at FROM medication_logs WHERE local_id = $1 AND client_id = $2
`

type GetMedicationLogByLocalIDParams struct {
	LocalID  pgtype.UUID `json:"local_id"`
	ClientID pgtype.UUID `json:"client_id"`
}

func (q *Queries) GetMedicationLogByLocalID(ctx context.Context, arg GetMedicationLogByLocalIDParams) (MedicationLog, error) {
	row := q.db.QueryRow(ctx, getMedicationLogByLocalID, arg.LocalID, arg.ClientID)
	var i MedicationLog
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.LocalID,
		&i.Date,
		&i.PrescribedMedicationID,
		&i.MedicationName,
		&i.Dosage,
		&i.TakenAt,
		&i.Notes,
		&i.IsSelfReported,
		&i.CreatedAt,
	)
	return i, err
}

const listMedicationLogsByDate = `-- name: ListMedicationLogsByDate :many
SELECT id, client_id, local_id, date, prescribed_medication_id, medication_name, dosage, taken_at, notes, is_self_reported, created_at FROM medication_logs WHERE client_id = $1 AND date = $2 ORDER BY taken_at ASC
`

type ListMedicationLogsByDateParams struct {
	ClientID pgtype.UUID `json:"client_id"`
	Date     pgtype.Date `json:"date"`
}

func (q *Queries) ListMedicationLogsByDate(ctx context.Context, arg ListMedicationLogsByDateParams) ([]MedicationLog, error) {
	rows, err := q.db.Query(ctx, listMedicationLogsByDate, arg.ClientID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MedicationLog{}
	for rows.Next() {
		var i MedicationLog
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.LocalID,
			&i.Date,
			&i.PrescribedMedicationID,
			&i.MedicationName,
			&i.Dosage,
			&i.TakenAt,
			&i.Notes,
			&i.IsSelfReported,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMedicationLogsForNutritionist = `-- name: ListMedicationLogsForNutritionist :many
SELECT ml.id, ml.client_id, ml.local_id, ml.date, ml.prescribed_medication_id, ml.medication_name, ml.dosage, ml.taken_at, ml.notes, ml.is_self_reported, ml.created_at FROM medication_logs ml
JOIN users u ON u.id = ml.client_id AND u.nutritionist_id = $1
WHERE ml.client_id = $2 AND ml.date BETWEEN $3 AND $4
ORDER BY ml.date DESC, ml.taken_at DESC
`

type ListMedicationLogsForNutritionistParams struct {
	NutritionistID pgtype.UUID `json:"nutritionist_id"`
	ClientID       pgtype.UUID `json:"client_id"`
	FromDate       pgtype.Date `json:"from_date"`
	ToDate         pgtype.Date `json:"to_date"`
}

func (q *Queries) ListMedicationLogsForNutritionist(ctx context.Context, arg ListMedicationLogsForNutritionistParams) ([]MedicationLog, error) {
	rows, err := q.db.Query(ctx, listMedicationLogsForNutritionist,
		arg.NutritionistID,
		arg.ClientID,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MedicationLog{}
	for rows.Next() {
		var i MedicationLog
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.LocalID,
			&i.Date,
			&i.PrescribedMedicationID,
			&i.MedicationName,
			&i.Dosage,
			&i.TakenAt,
			&i.Notes,
			&i.IsSelfReported,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
