// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: medications.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkDuplicateMedicationName = `-- name: CheckDuplicateMedicationName :one
SELECT EXISTS(
  SELECT 1 FROM medications
  WHERE LOWER(normalize_persian(name)) = LOWER(normalize_persian($1))
    AND is_active = true
    AND id != COALESCE($2::uuid, '00000000-0000-0000-0000-000000000000'::uuid)
) AS is_duplicate
`

type CheckDuplicateMedicationNameParams struct {
	Name      string      `json:"name"`
	ExcludeID pgtype.UUID `json:"exclude_id"`
}

func (q *Queries) CheckDuplicateMedicationName(ctx context.Context, arg CheckDuplicateMedicationNameParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkDuplicateMedicationName, arg.Name, arg.ExcludeID)
	var is_duplicate bool
	err := row.Scan(&is_duplicate)
	return is_duplicate, err
}

const countMedications = `-- name: CountMedications :one
SELECT COUNT(*)
FROM medications m
WHERE m.is_active = COALESCE($1::boolean, true)
  AND ($2::text IS NULL
    OR m.name_normalized ILIKE '%' || LOWER(normalize_persian($2::text)) || '%'
    OR (m.generic_name_normalized IS NOT NULL
        AND m.generic_name_normalized ILIKE '%' || LOWER(normalize_persian($2::text)) || '%'))
`

type CountMedicationsParams struct {
	IsActive pgtype.Bool `json:"is_active"`
	Search   pgtype.Text `json:"search"`
}

func (q *Queries) CountMedications(ctx context.Context, arg CountMedicationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMedications, arg.IsActive, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMedication = `-- name: CreateMedication :one
INSERT INTO medications (
    name, name_normalized, generic_name, generic_name_normalized, form, dosage_unit, description, created_by
) VALUES (
    $1,
    LOWER(normalize_persian($1)),
    $2,
    CASE WHEN $2::text IS NOT NULL THEN LOWER(normalize_persian($2::text)) ELSE NULL END,
    $3::medication_form,
    $4,
    $5,
    $6
) RETURNING id, name, name_normalized, generic_name, generic_name_normalized, form, dosage_unit, description, is_active, created_by, created_at, updated_at
`

type CreateMedicationParams struct {
	Name        string         `json:"name"`
	GenericName pgtype.Text    `json:"generic_name"`
	Form        MedicationForm `json:"form"`
	DosageUnit  pgtype.Text    `json:"dosage_unit"`
	Description pgtype.Text    `json:"description"`
	CreatedBy   pgtype.UUID    `json:"created_by"`
}

func (q *Queries) CreateMedication(ctx context.Context, arg CreateMedicationParams) (Medication, error) {
	row := q.db.QueryRow(ctx, createMedication,
		arg.Name,
		arg.GenericName,
		arg.Form,
		arg.DosageUnit,
		arg.Description,
		arg.CreatedBy,
	)
	var i Medication
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameNormalized,
		&i.GenericName,
		&i.GenericNameNormalized,
		&i.Form,
		&i.DosageUnit,
		&i.Description,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMedicationByID = `-- name: GetMedicationByID :one
SELECT m.id, m.name, m.name_normalized, m.generic_name, m.generic_name_normalized, m.form, m.dosage_unit, m.description, m.is_active, m.created_by, m.created_at, m.updated_at, u.full_name AS creator_name
FROM medications m
JOIN users u ON m.created_by = u.id
WHERE m.id = $1
`

type GetMedicationByIDRow struct {
	ID                    pgtype.UUID        `json:"id"`
	Name                  string             `json:"name"`
	NameNormalized        string             `json:"name_normalized"`
	GenericName           pgtype.Text        `json:"generic_name"`
	GenericNameNormalized pgtype.Text        `json:"generic_name_normalized"`
	Form                  MedicationForm     `json:"form"`
	DosageUnit            pgtype.Text        `json:"dosage_unit"`
	Description           pgtype.Text        `json:"description"`
	IsActive              bool               `json:"is_active"`
	CreatedBy             pgtype.UUID        `json:"created_by"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	CreatorName           string             `json:"creator_name"`
}

func (q *Queries) GetMedicationByID(ctx context.Context, id pgtype.UUID) (GetMedicationByIDRow, error) {
	row := q.db.QueryRow(ctx, getMedicationByID, id)
	var i GetMedicationByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameNormalized,
		&i.GenericName,
		&i.GenericNameNormalized,
		&i.Form,
		&i.DosageUnit,
		&i.Description,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatorName,
	)
	return i, err
}

const listMedications = `-- name: ListMedications :many
SELECT m.id, m.name, m.name_normalized, m.generic_name, m.generic_name_normalized, m.form, m.dosage_unit, m.description, m.is_active, m.created_by, m.created_at, m.updated_at, u.full_name AS creator_name
FROM medications m
JOIN users u ON m.created_by = u.id
WHERE m.is_active = COALESCE($1::boolean, true)
  AND ($2::text IS NULL
    OR m.name_normalized ILIKE '%' || LOWER(normalize_persian($2::text)) || '%'
    OR (m.generic_name_normalized IS NOT NULL
        AND m.generic_name_normalized ILIKE '%' || LOWER(normalize_persian($2::text)) || '%'))
ORDER BY
  CASE WHEN $2::text IS NOT NULL
    THEN similarity(m.name_normalized, LOWER(normalize_persian($2::text)))
    ELSE 0 END DESC,
  m.created_at DESC
LIMIT $4::bigint
OFFSET $3::bigint
`

type ListMedicationsParams struct {
	IsActive  pgtype.Bool `json:"is_active"`
	Search    pgtype.Text `json:"search"`
	OffsetVal int64       `json:"offset_val"`
	LimitVal  int64       `json:"limit_val"`
}

type ListMedicationsRow struct {
	ID                    pgtype.UUID        `json:"id"`
	Name                  string             `json:"name"`
	NameNormalized        string             `json:"name_normalized"`
	GenericName           pgtype.Text        `json:"generic_name"`
	GenericNameNormalized pgtype.Text        `json:"generic_name_normalized"`
	Form                  MedicationForm     `json:"form"`
	DosageUnit            pgtype.Text        `json:"dosage_unit"`
	Description           pgtype.Text        `json:"description"`
	IsActive              bool               `json:"is_active"`
	CreatedBy             pgtype.UUID        `json:"created_by"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	CreatorName           string             `json:"creator_name"`
}

func (q *Queries) ListMedications(ctx context.Context, arg ListMedicationsParams) ([]ListMedicationsRow, error) {
	rows, err := q.db.Query(ctx, listMedications,
		arg.IsActive,
		arg.Search,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMedicationsRow{}
	for rows.Next() {
		var i ListMedicationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameNormalized,
			&i.GenericName,
			&i.GenericNameNormalized,
			&i.Form,
			&i.DosageUnit,
			&i.Description,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteMedication = `-- name: SoftDeleteMedication :exec
UPDATE medications SET is_active = false, updated_at = NOW() WHERE id = $1
`

func (q *Queries) SoftDeleteMedication(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteMedication, id)
	return err
}

const softDeleteMedicationByOwner = `-- name: SoftDeleteMedicationByOwner :exec
UPDATE medications SET is_active = false, updated_at = NOW() WHERE id = $1 AND created_by = $2
`

type SoftDeleteMedicationByOwnerParams struct {
	ID        pgtype.UUID `json:"id"`
	CreatedBy pgtype.UUID `json:"created_by"`
}

func (q *Queries) SoftDeleteMedicationByOwner(ctx context.Context, arg SoftDeleteMedicationByOwnerParams) error {
	_, err := q.db.Exec(ctx, softDeleteMedicationByOwner, arg.ID, arg.CreatedBy)
	return err
}

const updateMedication = `-- name: UpdateMedication :one
UPDATE medications
SET name = $1,
    name_normalized = LOWER(normalize_persian($1)),
    generic_name = $2,
    generic_name_normalized = CASE WHEN $2::text IS NOT NULL THEN LOWER(normalize_persian($2::text)) ELSE NULL END,
    form = $3::medication_form,
    dosage_unit = $4,
    description = $5,
    updated_at = NOW()
WHERE id = $6
RETURNING id, name, name_normalized, generic_name, generic_name_normalized, form, dosage_unit, description, is_active, created_by, created_at, updated_at
`

type UpdateMedicationParams struct {
	Name        string         `json:"name"`
	GenericName pgtype.Text    `json:"generic_name"`
	Form        MedicationForm `json:"form"`
	DosageUnit  pgtype.Text    `json:"dosage_unit"`
	Description pgtype.Text    `json:"description"`
	ID          pgtype.UUID    `json:"id"`
}

func (q *Queries) UpdateMedication(ctx context.Context, arg UpdateMedicationParams) (Medication, error) {
	row := q.db.QueryRow(ctx, updateMedication,
		arg.Name,
		arg.GenericName,
		arg.Form,
		arg.DosageUnit,
		arg.Description,
		arg.ID,
	)
	var i Medication
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameNormalized,
		&i.GenericName,
		&i.GenericNameNormalized,
		&i.Form,
		&i.DosageUnit,
		&i.Description,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
