// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (sender_id, receiver_id, content, attachment_type, attachment_path, attachment_name)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, sender_id, receiver_id, content, attachment_type, attachment_path, attachment_name, sent_at, read_at
`

type CreateMessageParams struct {
	SenderID       pgtype.UUID `json:"sender_id"`
	ReceiverID     pgtype.UUID `json:"receiver_id"`
	Content        pgtype.Text `json:"content"`
	AttachmentType pgtype.Text `json:"attachment_type"`
	AttachmentPath pgtype.Text `json:"attachment_path"`
	AttachmentName pgtype.Text `json:"attachment_name"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.SenderID,
		arg.ReceiverID,
		arg.Content,
		arg.AttachmentType,
		arg.AttachmentPath,
		arg.AttachmentName,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.ReceiverID,
		&i.Content,
		&i.AttachmentType,
		&i.AttachmentPath,
		&i.AttachmentName,
		&i.SentAt,
		&i.ReadAt,
	)
	return i, err
}

const listMessages = `-- name: ListMessages :many
SELECT id, sender_id, receiver_id, content, attachment_type, attachment_path, attachment_name, sent_at, read_at
FROM messages
WHERE (sender_id = $1 AND receiver_id = $2)
   OR (sender_id = $2 AND receiver_id = $1)
ORDER BY sent_at ASC
LIMIT $3 OFFSET $4
`

type ListMessagesParams struct {
	UserA  pgtype.UUID `json:"user_a"`
	UserB  pgtype.UUID `json:"user_b"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessages, arg.UserA, arg.UserB, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.ReceiverID,
			&i.Content,
			&i.AttachmentType,
			&i.AttachmentPath,
			&i.AttachmentName,
			&i.SentAt,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesSince = `-- name: ListMessagesSince :many
SELECT id, sender_id, receiver_id, content, attachment_type, attachment_path, attachment_name, sent_at, read_at
FROM messages
WHERE ((sender_id = $1 AND receiver_id = $2) OR (sender_id = $2 AND receiver_id = $1))
  AND sent_at > $3
ORDER BY sent_at ASC
`

type ListMessagesSinceParams struct {
	UserA pgtype.UUID        `json:"user_a"`
	UserB pgtype.UUID        `json:"user_b"`
	Since pgtype.Timestamptz `json:"since"`
}

func (q *Queries) ListMessagesSince(ctx context.Context, arg ListMessagesSinceParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesSince, arg.UserA, arg.UserB, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.ReceiverID,
			&i.Content,
			&i.AttachmentType,
			&i.AttachmentPath,
			&i.AttachmentName,
			&i.SentAt,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMessagesRead = `-- name: MarkMessagesRead :exec
UPDATE messages
SET read_at = NOW()
WHERE receiver_id = $1
  AND sender_id = $2
  AND read_at IS NULL
`

type MarkMessagesReadParams struct {
	ReceiverID pgtype.UUID `json:"receiver_id"`
	SenderID   pgtype.UUID `json:"sender_id"`
}

func (q *Queries) MarkMessagesRead(ctx context.Context, arg MarkMessagesReadParams) error {
	_, err := q.db.Exec(ctx, markMessagesRead, arg.ReceiverID, arg.SenderID)
	return err
}

const countUnreadMessages = `-- name: CountUnreadMessages :one
SELECT COUNT(*)::integer
FROM messages
WHERE receiver_id = $1
  AND read_at IS NULL
`

func (q *Queries) CountUnreadMessages(ctx context.Context, receiverID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countUnreadMessages, receiverID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT id, sender_id, receiver_id, content, attachment_type, attachment_path, attachment_name, sent_at, read_at
FROM messages
WHERE id = $1
`

func (q *Queries) GetMessageByID(ctx context.Context, id pgtype.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, getMessageByID, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.ReceiverID,
		&i.Content,
		&i.AttachmentType,
		&i.AttachmentPath,
		&i.AttachmentName,
		&i.SentAt,
		&i.ReadAt,
	)
	return i, err
}
