// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type FoodCategoryType string

const (
	FoodCategoryTypeBreakfast  FoodCategoryType = "breakfast"
	FoodCategoryTypeLunch      FoodCategoryType = "lunch"
	FoodCategoryTypeDinner     FoodCategoryType = "dinner"
	FoodCategoryTypeSnack      FoodCategoryType = "snack"
	FoodCategoryTypeFruit      FoodCategoryType = "fruit"
	FoodCategoryTypeBeverage   FoodCategoryType = "beverage"
	FoodCategoryTypeSupplement FoodCategoryType = "supplement"
	FoodCategoryTypeOther      FoodCategoryType = "other"
)

func (e *FoodCategoryType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FoodCategoryType(s)
	case string:
		*e = FoodCategoryType(s)
	default:
		return fmt.Errorf("unsupported scan type for FoodCategoryType: %T", src)
	}
	return nil
}

type NullFoodCategoryType struct {
	FoodCategoryType FoodCategoryType `json:"food_category_type"`
	Valid            bool             `json:"valid"` // Valid is true if FoodCategoryType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFoodCategoryType) Scan(value interface{}) error {
	if value == nil {
		ns.FoodCategoryType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FoodCategoryType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFoodCategoryType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FoodCategoryType), nil
}

type GenderType string

const (
	GenderTypeMale   GenderType = "male"
	GenderTypeFemale GenderType = "female"
)

func (e *GenderType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GenderType(s)
	case string:
		*e = GenderType(s)
	default:
		return fmt.Errorf("unsupported scan type for GenderType: %T", src)
	}
	return nil
}

type NullGenderType struct {
	GenderType GenderType `json:"gender_type"`
	Valid      bool       `json:"valid"` // Valid is true if GenderType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGenderType) Scan(value interface{}) error {
	if value == nil {
		ns.GenderType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GenderType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGenderType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GenderType), nil
}

type MeasurementUnitType string

const (
	MeasurementUnitTypeGram       MeasurementUnitType = "gram"
	MeasurementUnitTypeKg         MeasurementUnitType = "kg"
	MeasurementUnitTypeTablespoon MeasurementUnitType = "tablespoon"
	MeasurementUnitTypeTeaspoon   MeasurementUnitType = "teaspoon"
	MeasurementUnitTypeCup        MeasurementUnitType = "cup"
	MeasurementUnitTypePiece      MeasurementUnitType = "piece"
	MeasurementUnitTypeSlice      MeasurementUnitType = "slice"
	MeasurementUnitTypePalm       MeasurementUnitType = "palm"
	MeasurementUnitTypeMatchbox   MeasurementUnitType = "matchbox"
	MeasurementUnitTypeBowl       MeasurementUnitType = "bowl"
	MeasurementUnitTypeMl         MeasurementUnitType = "ml"
	MeasurementUnitTypeLiter      MeasurementUnitType = "liter"
)

func (e *MeasurementUnitType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MeasurementUnitType(s)
	case string:
		*e = MeasurementUnitType(s)
	default:
		return fmt.Errorf("unsupported scan type for MeasurementUnitType: %T", src)
	}
	return nil
}

type NullMeasurementUnitType struct {
	MeasurementUnitType MeasurementUnitType `json:"measurement_unit_type"`
	Valid               bool                `json:"valid"` // Valid is true if MeasurementUnitType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMeasurementUnitType) Scan(value interface{}) error {
	if value == nil {
		ns.MeasurementUnitType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MeasurementUnitType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMeasurementUnitType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MeasurementUnitType), nil
}

type MedicationForm string

const (
	MedicationFormTablet    MedicationForm = "tablet"
	MedicationFormCapsule   MedicationForm = "capsule"
	MedicationFormSyrup     MedicationForm = "syrup"
	MedicationFormInjection MedicationForm = "injection"
	MedicationFormDrop      MedicationForm = "drop"
	MedicationFormPowder    MedicationForm = "powder"
	MedicationFormOther     MedicationForm = "other"
)

func (e *MedicationForm) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MedicationForm(s)
	case string:
		*e = MedicationForm(s)
	default:
		return fmt.Errorf("unsupported scan type for MedicationForm: %T", src)
	}
	return nil
}

type NullMedicationForm struct {
	MedicationForm MedicationForm `json:"medication_form"`
	Valid          bool           `json:"valid"` // Valid is true if MedicationForm is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMedicationForm) Scan(value interface{}) error {
	if value == nil {
		ns.MedicationForm, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MedicationForm.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMedicationForm) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MedicationForm), nil
}

type UserRole string

const (
	UserRoleSuperAdmin   UserRole = "super_admin"
	UserRoleNutritionist UserRole = "nutritionist"
	UserRoleClient       UserRole = "client"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Food struct {
	ID                pgtype.UUID         `json:"id"`
	Name              string              `json:"name"`
	NameNormalized    string              `json:"name_normalized"`
	Description       pgtype.Text         `json:"description"`
	Calories          pgtype.Numeric      `json:"calories"`
	ProteinG          pgtype.Numeric      `json:"protein_g"`
	CarbsG            pgtype.Numeric      `json:"carbs_g"`
	FatG              pgtype.Numeric      `json:"fat_g"`
	FiberG            pgtype.Numeric      `json:"fiber_g"`
	SugarG            pgtype.Numeric      `json:"sugar_g"`
	SodiumMg          pgtype.Numeric      `json:"sodium_mg"`
	MeasurementUnit   MeasurementUnitType `json:"measurement_unit"`
	MeasurementAmount pgtype.Numeric      `json:"measurement_amount"`
	IsActive          bool                `json:"is_active"`
	CreatedBy         pgtype.UUID         `json:"created_by"`
	CreatedAt         pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz  `json:"updated_at"`
}

type FoodCategory struct {
	FoodID   pgtype.UUID      `json:"food_id"`
	Category FoodCategoryType `json:"category"`
}

type Medication struct {
	ID                    pgtype.UUID        `json:"id"`
	Name                  string             `json:"name"`
	NameNormalized        string             `json:"name_normalized"`
	GenericName           pgtype.Text        `json:"generic_name"`
	GenericNameNormalized pgtype.Text        `json:"generic_name_normalized"`
	Form                  MedicationForm     `json:"form"`
	DosageUnit            pgtype.Text        `json:"dosage_unit"`
	Description           pgtype.Text        `json:"description"`
	IsActive              bool               `json:"is_active"`
	CreatedBy             pgtype.UUID        `json:"created_by"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type OtpCode struct {
	ID          pgtype.UUID        `json:"id"`
	Mobile      string             `json:"mobile"`
	CodeHash    string             `json:"code_hash"`
	Attempts    int32              `json:"attempts"`
	MaxAttempts int32              `json:"max_attempts"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	Verified    bool               `json:"verified"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type RefreshToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	FamilyID  pgtype.UUID        `json:"family_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Revoked   bool               `json:"revoked"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID             pgtype.UUID        `json:"id"`
	Role           UserRole           `json:"role"`
	FullName       string             `json:"full_name"`
	Email          pgtype.Text        `json:"email"`
	PasswordHash   pgtype.Text        `json:"password_hash"`
	Mobile         pgtype.Text        `json:"mobile"`
	DateOfBirth    pgtype.Date        `json:"date_of_birth"`
	HeightCm       pgtype.Float4      `json:"height_cm"`
	Gender         NullGenderType     `json:"gender"`
	NutritionistID pgtype.UUID        `json:"nutritionist_id"`
	IsActive       bool               `json:"is_active"`
	Notes          pgtype.Text        `json:"notes"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}
