// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type DietPlanStatus string

const (
	DietPlanStatusDraft    DietPlanStatus = "draft"
	DietPlanStatusActive   DietPlanStatus = "active"
	DietPlanStatusArchived DietPlanStatus = "archived"
)

func (e *DietPlanStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DietPlanStatus(s)
	case string:
		*e = DietPlanStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DietPlanStatus: %T", src)
	}
	return nil
}

type NullDietPlanStatus struct {
	DietPlanStatus DietPlanStatus `json:"diet_plan_status"`
	Valid          bool           `json:"valid"` // Valid is true if DietPlanStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDietPlanStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DietPlanStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DietPlanStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDietPlanStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DietPlanStatus), nil
}

type FoodRequestStatus string

const (
	FoodRequestStatusPending  FoodRequestStatus = "pending"
	FoodRequestStatusApproved FoodRequestStatus = "approved"
	FoodRequestStatusRejected FoodRequestStatus = "rejected"
)

func (e *FoodRequestStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FoodRequestStatus(s)
	case string:
		*e = FoodRequestStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for FoodRequestStatus: %T", src)
	}
	return nil
}

type NullFoodRequestStatus struct {
	FoodRequestStatus FoodRequestStatus `json:"food_request_status"`
	Valid             bool              `json:"valid"` // Valid is true if FoodRequestStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFoodRequestStatus) Scan(value interface{}) error {
	if value == nil {
		ns.FoodRequestStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FoodRequestStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFoodRequestStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FoodRequestStatus), nil
}

type FoodCategoryType string

const (
	FoodCategoryTypeBreakfast  FoodCategoryType = "breakfast"
	FoodCategoryTypeLunch      FoodCategoryType = "lunch"
	FoodCategoryTypeDinner     FoodCategoryType = "dinner"
	FoodCategoryTypeSnack      FoodCategoryType = "snack"
	FoodCategoryTypeFruit      FoodCategoryType = "fruit"
	FoodCategoryTypeBeverage   FoodCategoryType = "beverage"
	FoodCategoryTypeSupplement FoodCategoryType = "supplement"
	FoodCategoryTypeOther      FoodCategoryType = "other"
)

func (e *FoodCategoryType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FoodCategoryType(s)
	case string:
		*e = FoodCategoryType(s)
	default:
		return fmt.Errorf("unsupported scan type for FoodCategoryType: %T", src)
	}
	return nil
}

type NullFoodCategoryType struct {
	FoodCategoryType FoodCategoryType `json:"food_category_type"`
	Valid            bool             `json:"valid"` // Valid is true if FoodCategoryType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFoodCategoryType) Scan(value interface{}) error {
	if value == nil {
		ns.FoodCategoryType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FoodCategoryType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFoodCategoryType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FoodCategoryType), nil
}

type GenderType string

const (
	GenderTypeMale   GenderType = "male"
	GenderTypeFemale GenderType = "female"
)

func (e *GenderType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GenderType(s)
	case string:
		*e = GenderType(s)
	default:
		return fmt.Errorf("unsupported scan type for GenderType: %T", src)
	}
	return nil
}

type NullGenderType struct {
	GenderType GenderType `json:"gender_type"`
	Valid      bool       `json:"valid"` // Valid is true if GenderType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGenderType) Scan(value interface{}) error {
	if value == nil {
		ns.GenderType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GenderType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGenderType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GenderType), nil
}

type LabResultType string

const (
	LabResultTypeBloodTest LabResultType = "blood_test"
	LabResultTypeUrineTest LabResultType = "urine_test"
	LabResultTypeThyroid   LabResultType = "thyroid"
	LabResultTypeHormone   LabResultType = "hormone"
	LabResultTypeAllergy   LabResultType = "allergy"
	LabResultTypeOther     LabResultType = "other"
)

func (e *LabResultType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LabResultType(s)
	case string:
		*e = LabResultType(s)
	default:
		return fmt.Errorf("unsupported scan type for LabResultType: %T", src)
	}
	return nil
}

type NullLabResultType struct {
	LabResultType LabResultType `json:"lab_result_type"`
	Valid         bool          `json:"valid"` // Valid is true if LabResultType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLabResultType) Scan(value interface{}) error {
	if value == nil {
		ns.LabResultType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LabResultType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLabResultType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LabResultType), nil
}

type MeasurementUnitType string

const (
	MeasurementUnitTypeGram       MeasurementUnitType = "gram"
	MeasurementUnitTypeKg         MeasurementUnitType = "kg"
	MeasurementUnitTypeTablespoon MeasurementUnitType = "tablespoon"
	MeasurementUnitTypeTeaspoon   MeasurementUnitType = "teaspoon"
	MeasurementUnitTypeCup        MeasurementUnitType = "cup"
	MeasurementUnitTypePiece      MeasurementUnitType = "piece"
	MeasurementUnitTypeSlice      MeasurementUnitType = "slice"
	MeasurementUnitTypePalm       MeasurementUnitType = "palm"
	MeasurementUnitTypeMatchbox   MeasurementUnitType = "matchbox"
	MeasurementUnitTypeBowl       MeasurementUnitType = "bowl"
	MeasurementUnitTypeMl         MeasurementUnitType = "ml"
	MeasurementUnitTypeLiter      MeasurementUnitType = "liter"
)

func (e *MeasurementUnitType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MeasurementUnitType(s)
	case string:
		*e = MeasurementUnitType(s)
	default:
		return fmt.Errorf("unsupported scan type for MeasurementUnitType: %T", src)
	}
	return nil
}

type NullMeasurementUnitType struct {
	MeasurementUnitType MeasurementUnitType `json:"measurement_unit_type"`
	Valid               bool                `json:"valid"` // Valid is true if MeasurementUnitType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMeasurementUnitType) Scan(value interface{}) error {
	if value == nil {
		ns.MeasurementUnitType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MeasurementUnitType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMeasurementUnitType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MeasurementUnitType), nil
}

type MedicationForm string

const (
	MedicationFormTablet    MedicationForm = "tablet"
	MedicationFormCapsule   MedicationForm = "capsule"
	MedicationFormSyrup     MedicationForm = "syrup"
	MedicationFormInjection MedicationForm = "injection"
	MedicationFormDrop      MedicationForm = "drop"
	MedicationFormPowder    MedicationForm = "powder"
	MedicationFormOther     MedicationForm = "other"
)

func (e *MedicationForm) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MedicationForm(s)
	case string:
		*e = MedicationForm(s)
	default:
		return fmt.Errorf("unsupported scan type for MedicationForm: %T", src)
	}
	return nil
}

type NullMedicationForm struct {
	MedicationForm MedicationForm `json:"medication_form"`
	Valid          bool           `json:"valid"` // Valid is true if MedicationForm is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMedicationForm) Scan(value interface{}) error {
	if value == nil {
		ns.MedicationForm, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MedicationForm.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMedicationForm) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MedicationForm), nil
}

type SleepQuality string

const (
	SleepQualityGood SleepQuality = "good"
	SleepQualityFair SleepQuality = "fair"
	SleepQualityPoor SleepQuality = "poor"
)

func (e *SleepQuality) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SleepQuality(s)
	case string:
		*e = SleepQuality(s)
	default:
		return fmt.Errorf("unsupported scan type for SleepQuality: %T", src)
	}
	return nil
}

type NullSleepQuality struct {
	SleepQuality SleepQuality `json:"sleep_quality"`
	Valid        bool         `json:"valid"` // Valid is true if SleepQuality is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSleepQuality) Scan(value interface{}) error {
	if value == nil {
		ns.SleepQuality, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SleepQuality.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSleepQuality) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SleepQuality), nil
}

type UserRole string

const (
	UserRoleSuperAdmin   UserRole = "super_admin"
	UserRoleNutritionist UserRole = "nutritionist"
	UserRoleClient       UserRole = "client"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type BodyMeasurement struct {
	ID         pgtype.UUID        `json:"id"`
	ClientID   pgtype.UUID        `json:"client_id"`
	LocalID    pgtype.UUID        `json:"local_id"`
	Date       pgtype.Date        `json:"date"`
	WeightKg   pgtype.Numeric     `json:"weight_kg"`
	WaistCm    pgtype.Numeric     `json:"waist_cm"`
	HipCm      pgtype.Numeric     `json:"hip_cm"`
	AbdomenCm  pgtype.Numeric     `json:"abdomen_cm"`
	ThighCm    pgtype.Numeric     `json:"thigh_cm"`
	ChestCm    pgtype.Numeric     `json:"chest_cm"`
	WristCm    pgtype.Numeric     `json:"wrist_cm"`
	RecordedBy pgtype.UUID        `json:"recorded_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type DietPlan struct {
	ID                 pgtype.UUID        `json:"id"`
	ClientID           pgtype.UUID        `json:"client_id"`
	NutritionistID     pgtype.UUID        `json:"nutritionist_id"`
	StartDate          pgtype.Date        `json:"start_date"`
	EndDate            pgtype.Date        `json:"end_date"`
	Notes              pgtype.Text        `json:"notes"`
	DailyWaterTargetMl pgtype.Int4        `json:"daily_water_target_ml"`
	Status             DietPlanStatus     `json:"status"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type ExerciseLog struct {
	ID              pgtype.UUID        `json:"id"`
	ClientID        pgtype.UUID        `json:"client_id"`
	LocalID         pgtype.UUID        `json:"local_id"`
	Date            pgtype.Date        `json:"date"`
	ExerciseName    string             `json:"exercise_name"`
	DurationMinutes int32              `json:"duration_minutes"`
	CaloriesBurned  pgtype.Int4        `json:"calories_burned"`
	Notes           pgtype.Text        `json:"notes"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Food struct {
	ID                pgtype.UUID         `json:"id"`
	Name              string              `json:"name"`
	NameNormalized    string              `json:"name_normalized"`
	Description       pgtype.Text         `json:"description"`
	Calories          pgtype.Numeric      `json:"calories"`
	ProteinG          pgtype.Numeric      `json:"protein_g"`
	CarbsG            pgtype.Numeric      `json:"carbs_g"`
	FatG              pgtype.Numeric      `json:"fat_g"`
	FiberG            pgtype.Numeric      `json:"fiber_g"`
	SugarG            pgtype.Numeric      `json:"sugar_g"`
	SodiumMg          pgtype.Numeric      `json:"sodium_mg"`
	MeasurementUnit   MeasurementUnitType `json:"measurement_unit"`
	MeasurementAmount pgtype.Numeric      `json:"measurement_amount"`
	IsActive          bool                `json:"is_active"`
	CreatedBy         pgtype.UUID         `json:"created_by"`
	CreatedAt         pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz  `json:"updated_at"`
}

type FoodCategory struct {
	FoodID   pgtype.UUID      `json:"food_id"`
	Category FoodCategoryType `json:"category"`
}

type FoodLog struct {
	ID               pgtype.UUID        `json:"id"`
	ClientID         pgtype.UUID        `json:"client_id"`
	LocalID          pgtype.UUID        `json:"local_id"`
	Date             pgtype.Date        `json:"date"`
	MealID           pgtype.UUID        `json:"meal_id"`
	SelectedOptionID pgtype.UUID        `json:"selected_option_id"`
	IsSkipped        bool               `json:"is_skipped"`
	Notes            pgtype.Text        `json:"notes"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type LabResult struct {
	ID               pgtype.UUID        `json:"id"`
	ClientID         pgtype.UUID        `json:"client_id"`
	LocalID          pgtype.UUID        `json:"local_id"`
	UploadedBy       pgtype.UUID        `json:"uploaded_by"`
	Title            string             `json:"title"`
	LabType          LabResultType      `json:"lab_type"`
	TestDate         pgtype.Date        `json:"test_date"`
	FilePath         pgtype.Text        `json:"file_path"`
	ExternalLink     pgtype.Text        `json:"external_link"`
	OriginalFilename pgtype.Text        `json:"original_filename"`
	MimeType         pgtype.Text        `json:"mime_type"`
	FileSizeBytes    pgtype.Int8        `json:"file_size_bytes"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type Meal struct {
	ID            pgtype.UUID        `json:"id"`
	DayID         pgtype.UUID        `json:"day_id"`
	Title         string             `json:"title"`
	ScheduledTime pgtype.Time        `json:"scheduled_time"`
	DisplayOrder  int32              `json:"display_order"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type MealOption struct {
	ID           pgtype.UUID        `json:"id"`
	MealID       pgtype.UUID        `json:"meal_id"`
	OptionNumber int16              `json:"option_number"`
	Label        pgtype.Text        `json:"label"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type MealOptionItem struct {
	ID              pgtype.UUID         `json:"id"`
	OptionID        pgtype.UUID         `json:"option_id"`
	FoodID          pgtype.UUID         `json:"food_id"`
	Quantity        pgtype.Numeric      `json:"quantity"`
	MeasurementUnit MeasurementUnitType `json:"measurement_unit"`
	Notes           pgtype.Text         `json:"notes"`
	CreatedAt       pgtype.Timestamptz  `json:"created_at"`
}

type Medication struct {
	ID                    pgtype.UUID        `json:"id"`
	Name                  string             `json:"name"`
	NameNormalized        string             `json:"name_normalized"`
	GenericName           pgtype.Text        `json:"generic_name"`
	GenericNameNormalized pgtype.Text        `json:"generic_name_normalized"`
	Form                  MedicationForm     `json:"form"`
	DosageUnit            pgtype.Text        `json:"dosage_unit"`
	Description           pgtype.Text        `json:"description"`
	IsActive              bool               `json:"is_active"`
	CreatedBy             pgtype.UUID        `json:"created_by"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type MedicationLog struct {
	ID                     pgtype.UUID        `json:"id"`
	ClientID               pgtype.UUID        `json:"client_id"`
	LocalID                pgtype.UUID        `json:"local_id"`
	Date                   pgtype.Date        `json:"date"`
	PrescribedMedicationID pgtype.UUID        `json:"prescribed_medication_id"`
	MedicationName         string             `json:"medication_name"`
	Dosage                 pgtype.Text        `json:"dosage"`
	TakenAt                pgtype.Time        `json:"taken_at"`
	Notes                  pgtype.Text        `json:"notes"`
	IsSelfReported         bool               `json:"is_self_reported"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
}

type OtpCode struct {
	ID          pgtype.UUID        `json:"id"`
	Mobile      string             `json:"mobile"`
	CodeHash    string             `json:"code_hash"`
	Attempts    int32              `json:"attempts"`
	MaxAttempts int32              `json:"max_attempts"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	Verified    bool               `json:"verified"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type PlanDay struct {
	ID        pgtype.UUID        `json:"id"`
	PlanID    pgtype.UUID        `json:"plan_id"`
	DayNumber int32              `json:"day_number"`
	Label     pgtype.Text        `json:"label"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PlanExercise struct {
	ID                   pgtype.UUID        `json:"id"`
	DayID                pgtype.UUID        `json:"day_id"`
	ExerciseName         string             `json:"exercise_name"`
	DurationMinutes      int32              `json:"duration_minutes"`
	Description          pgtype.Text        `json:"description"`
	CaloriesBurnEstimate pgtype.Int4        `json:"calories_burn_estimate"`
	DisplayOrder         int32              `json:"display_order"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

type PlanMedication struct {
	ID           pgtype.UUID        `json:"id"`
	PlanID       pgtype.UUID        `json:"plan_id"`
	MedicationID pgtype.UUID        `json:"medication_id"`
	Dosage       string             `json:"dosage"`
	Frequency    string             `json:"frequency"`
	Times        []byte             `json:"times"`
	Instructions pgtype.Text        `json:"instructions"`
	StartDate    pgtype.Date        `json:"start_date"`
	EndDate      pgtype.Date        `json:"end_date"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type RefreshToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	FamilyID  pgtype.UUID        `json:"family_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Revoked   bool               `json:"revoked"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type SleepLog struct {
	ID        pgtype.UUID        `json:"id"`
	ClientID  pgtype.UUID        `json:"client_id"`
	LocalID   pgtype.UUID        `json:"local_id"`
	Date      pgtype.Date        `json:"date"`
	SleepTime pgtype.Time        `json:"sleep_time"`
	WakeTime  pgtype.Time        `json:"wake_time"`
	Quality   SleepQuality       `json:"quality"`
	Notes     pgtype.Text        `json:"notes"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID             pgtype.UUID        `json:"id"`
	Role           UserRole           `json:"role"`
	FullName       string             `json:"full_name"`
	Email          pgtype.Text        `json:"email"`
	PasswordHash   pgtype.Text        `json:"password_hash"`
	Mobile         pgtype.Text        `json:"mobile"`
	DateOfBirth    pgtype.Date        `json:"date_of_birth"`
	HeightCm       pgtype.Float4      `json:"height_cm"`
	Gender         NullGenderType     `json:"gender"`
	NutritionistID pgtype.UUID        `json:"nutritionist_id"`
	IsActive       bool               `json:"is_active"`
	Notes          pgtype.Text        `json:"notes"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type WaterLog struct {
	ID         pgtype.UUID        `json:"id"`
	ClientID   pgtype.UUID        `json:"client_id"`
	LocalID    pgtype.UUID        `json:"local_id"`
	Date       pgtype.Date        `json:"date"`
	AmountMl   int32              `json:"amount_ml"`
	LoggedTime pgtype.Time        `json:"logged_time"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Message struct {
	ID             pgtype.UUID        `json:"id"`
	SenderID       pgtype.UUID        `json:"sender_id"`
	ReceiverID     pgtype.UUID        `json:"receiver_id"`
	Content        pgtype.Text        `json:"content"`
	AttachmentType pgtype.Text        `json:"attachment_type"`
	AttachmentPath pgtype.Text        `json:"attachment_path"`
	AttachmentName pgtype.Text        `json:"attachment_name"`
	SentAt         pgtype.Timestamptz `json:"sent_at"`
	ReadAt         pgtype.Timestamptz `json:"read_at"`
}

type FoodRequest struct {
	ID              pgtype.UUID        `json:"id"`
	FoodName        string             `json:"food_name"`
	Description     pgtype.Text        `json:"description"`
	Status          FoodRequestStatus  `json:"status"`
	RejectionReason pgtype.Text        `json:"rejection_reason"`
	RequestedBy     pgtype.UUID        `json:"requested_by"`
	ReviewedBy      pgtype.UUID        `json:"reviewed_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}
