// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification_preferences.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getNotificationPreferences = `-- name: GetNotificationPreferences :one
SELECT client_id, new_message, plan_activated, food_request_decision, meal_reminder, medication_reminder, water_reminder, updated_at FROM notification_preferences WHERE client_id = $1
`

func (q *Queries) GetNotificationPreferences(ctx context.Context, clientID pgtype.UUID) (NotificationPreference, error) {
	row := q.db.QueryRow(ctx, getNotificationPreferences, clientID)
	var i NotificationPreference
	err := row.Scan(
		&i.ClientID,
		&i.NewMessage,
		&i.PlanActivated,
		&i.FoodRequestDecision,
		&i.MealReminder,
		&i.MedicationReminder,
		&i.WaterReminder,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertNotificationPreferences = `-- name: UpsertNotificationPreferences :one
INSERT INTO notification_preferences (client_id, new_message, plan_activated, food_request_decision,
  meal_reminder, medication_reminder, water_reminder)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (client_id) DO UPDATE
  SET new_message           = EXCLUDED.new_message,
      plan_activated        = EXCLUDED.plan_activated,
      food_request_decision = EXCLUDED.food_request_decision,
      meal_reminder         = EXCLUDED.meal_reminder,
      medication_reminder   = EXCLUDED.medication_reminder,
      water_reminder        = EXCLUDED.water_reminder,
      updated_at            = NOW()
RETURNING client_id, new_message, plan_activated, food_request_decision, meal_reminder, medication_reminder, water_reminder, updated_at
`

type UpsertNotificationPreferencesParams struct {
	ClientID            pgtype.UUID `json:"client_id"`
	NewMessage          bool        `json:"new_message"`
	PlanActivated       bool        `json:"plan_activated"`
	FoodRequestDecision bool        `json:"food_request_decision"`
	MealReminder        bool        `json:"meal_reminder"`
	MedicationReminder  bool        `json:"medication_reminder"`
	WaterReminder       bool        `json:"water_reminder"`
}

func (q *Queries) UpsertNotificationPreferences(ctx context.Context, arg UpsertNotificationPreferencesParams) (NotificationPreference, error) {
	row := q.db.QueryRow(ctx, upsertNotificationPreferences,
		arg.ClientID,
		arg.NewMessage,
		arg.PlanActivated,
		arg.FoodRequestDecision,
		arg.MealReminder,
		arg.MedicationReminder,
		arg.WaterReminder,
	)
	var i NotificationPreference
	err := row.Scan(
		&i.ClientID,
		&i.NewMessage,
		&i.PlanActivated,
		&i.FoodRequestDecision,
		&i.MealReminder,
		&i.MedicationReminder,
		&i.WaterReminder,
		&i.UpdatedAt,
	)
	return i, err
}
