// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: otp.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOTP = `-- name: CreateOTP :one
INSERT INTO otp_codes (
    mobile, code_hash, expires_at, max_attempts
) VALUES (
    $1, $2, $3, $4
) RETURNING id, mobile, code_hash, attempts, max_attempts, expires_at, verified, created_at
`

type CreateOTPParams struct {
	Mobile      string             `json:"mobile"`
	CodeHash    string             `json:"code_hash"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	MaxAttempts int32              `json:"max_attempts"`
}

func (q *Queries) CreateOTP(ctx context.Context, arg CreateOTPParams) (OtpCode, error) {
	row := q.db.QueryRow(ctx, createOTP,
		arg.Mobile,
		arg.CodeHash,
		arg.ExpiresAt,
		arg.MaxAttempts,
	)
	var i OtpCode
	err := row.Scan(
		&i.ID,
		&i.Mobile,
		&i.CodeHash,
		&i.Attempts,
		&i.MaxAttempts,
		&i.ExpiresAt,
		&i.Verified,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredOTPs = `-- name: DeleteExpiredOTPs :exec
DELETE FROM otp_codes
WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredOTPs(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredOTPs)
	return err
}

const getActiveOTPByMobile = `-- name: GetActiveOTPByMobile :one
SELECT id, mobile, code_hash, attempts, max_attempts, expires_at, verified, created_at FROM otp_codes
WHERE mobile = $1 AND expires_at > NOW() AND verified = false
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetActiveOTPByMobile(ctx context.Context, mobile string) (OtpCode, error) {
	row := q.db.QueryRow(ctx, getActiveOTPByMobile, mobile)
	var i OtpCode
	err := row.Scan(
		&i.ID,
		&i.Mobile,
		&i.CodeHash,
		&i.Attempts,
		&i.MaxAttempts,
		&i.ExpiresAt,
		&i.Verified,
		&i.CreatedAt,
	)
	return i, err
}

const incrementOTPAttempts = `-- name: IncrementOTPAttempts :exec
UPDATE otp_codes
SET attempts = attempts + 1
WHERE id = $1
`

func (q *Queries) IncrementOTPAttempts(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementOTPAttempts, id)
	return err
}

const markOTPVerified = `-- name: MarkOTPVerified :exec
UPDATE otp_codes
SET verified = true
WHERE id = $1
`

func (q *Queries) MarkOTPVerified(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markOTPVerified, id)
	return err
}
