// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plan_medications.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPlanMedication = `-- name: CreatePlanMedication :one
INSERT INTO plan_medications (plan_id, medication_id, dosage, frequency, times, instructions, start_date, end_date)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, plan_id, medication_id, dosage, frequency, times, instructions, start_date, end_date, created_at, updated_at
`

type CreatePlanMedicationParams struct {
	PlanID       pgtype.UUID `json:"plan_id"`
	MedicationID pgtype.UUID `json:"medication_id"`
	Dosage       string      `json:"dosage"`
	Frequency    string      `json:"frequency"`
	Times        []byte      `json:"times"`
	Instructions pgtype.Text `json:"instructions"`
	StartDate    pgtype.Date `json:"start_date"`
	EndDate      pgtype.Date `json:"end_date"`
}

func (q *Queries) CreatePlanMedication(ctx context.Context, arg CreatePlanMedicationParams) (PlanMedication, error) {
	row := q.db.QueryRow(ctx, createPlanMedication,
		arg.PlanID,
		arg.MedicationID,
		arg.Dosage,
		arg.Frequency,
		arg.Times,
		arg.Instructions,
		arg.StartDate,
		arg.EndDate,
	)
	var i PlanMedication
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.MedicationID,
		&i.Dosage,
		&i.Frequency,
		&i.Times,
		&i.Instructions,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePlanMedication = `-- name: DeletePlanMedication :exec
DELETE FROM plan_medications
WHERE id = $1 AND plan_id = $2
`

type DeletePlanMedicationParams struct {
	ID     pgtype.UUID `json:"id"`
	PlanID pgtype.UUID `json:"plan_id"`
}

func (q *Queries) DeletePlanMedication(ctx context.Context, arg DeletePlanMedicationParams) error {
	_, err := q.db.Exec(ctx, deletePlanMedication, arg.ID, arg.PlanID)
	return err
}

const getPlanMedicationByID = `-- name: GetPlanMedicationByID :one
SELECT id, plan_id, medication_id, dosage, frequency, times, instructions, start_date, end_date, created_at, updated_at FROM plan_medications
WHERE id = $1 AND plan_id = $2
`

type GetPlanMedicationByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	PlanID pgtype.UUID `json:"plan_id"`
}

func (q *Queries) GetPlanMedicationByID(ctx context.Context, arg GetPlanMedicationByIDParams) (PlanMedication, error) {
	row := q.db.QueryRow(ctx, getPlanMedicationByID, arg.ID, arg.PlanID)
	var i PlanMedication
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.MedicationID,
		&i.Dosage,
		&i.Frequency,
		&i.Times,
		&i.Instructions,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePlanMedication = `-- name: UpdatePlanMedication :one
UPDATE plan_medications
SET dosage        = $2,
    frequency     = $3,
    times         = $4,
    instructions  = $5,
    start_date    = $6,
    end_date      = $7,
    updated_at    = NOW()
WHERE id = $1
RETURNING id, plan_id, medication_id, dosage, frequency, times, instructions, start_date, end_date, created_at, updated_at
`

type UpdatePlanMedicationParams struct {
	ID           pgtype.UUID `json:"id"`
	Dosage       string      `json:"dosage"`
	Frequency    string      `json:"frequency"`
	Times        []byte      `json:"times"`
	Instructions pgtype.Text `json:"instructions"`
	StartDate    pgtype.Date `json:"start_date"`
	EndDate      pgtype.Date `json:"end_date"`
}

func (q *Queries) UpdatePlanMedication(ctx context.Context, arg UpdatePlanMedicationParams) (PlanMedication, error) {
	row := q.db.QueryRow(ctx, updatePlanMedication,
		arg.ID,
		arg.Dosage,
		arg.Frequency,
		arg.Times,
		arg.Instructions,
		arg.StartDate,
		arg.EndDate,
	)
	var i PlanMedication
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.MedicationID,
		&i.Dosage,
		&i.Frequency,
		&i.Times,
		&i.Instructions,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
