// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plan_days.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPlanDays = `-- name: CountPlanDays :one
SELECT COUNT(*) FROM plan_days WHERE plan_id = $1
`

func (q *Queries) CountPlanDays(ctx context.Context, planID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPlanDays, planID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPlanDay = `-- name: CreatePlanDay :one
INSERT INTO plan_days (plan_id, day_number, label)
VALUES ($1, $2, $3)
RETURNING id, plan_id, day_number, label, created_at
`

type CreatePlanDayParams struct {
	PlanID    pgtype.UUID `json:"plan_id"`
	DayNumber int32       `json:"day_number"`
	Label     pgtype.Text `json:"label"`
}

func (q *Queries) CreatePlanDay(ctx context.Context, arg CreatePlanDayParams) (PlanDay, error) {
	row := q.db.QueryRow(ctx, createPlanDay, arg.PlanID, arg.DayNumber, arg.Label)
	var i PlanDay
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.DayNumber,
		&i.Label,
		&i.CreatedAt,
	)
	return i, err
}

const deletePlanDay = `-- name: DeletePlanDay :exec
DELETE FROM plan_days
WHERE id = $1 AND plan_id = $2
`

type DeletePlanDayParams struct {
	ID     pgtype.UUID `json:"id"`
	PlanID pgtype.UUID `json:"plan_id"`
}

func (q *Queries) DeletePlanDay(ctx context.Context, arg DeletePlanDayParams) error {
	_, err := q.db.Exec(ctx, deletePlanDay, arg.ID, arg.PlanID)
	return err
}

const getPlanDayByID = `-- name: GetPlanDayByID :one
SELECT id, plan_id, day_number, label, created_at FROM plan_days
WHERE id = $1 AND plan_id = $2
`

type GetPlanDayByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	PlanID pgtype.UUID `json:"plan_id"`
}

func (q *Queries) GetPlanDayByID(ctx context.Context, arg GetPlanDayByIDParams) (PlanDay, error) {
	row := q.db.QueryRow(ctx, getPlanDayByID, arg.ID, arg.PlanID)
	var i PlanDay
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.DayNumber,
		&i.Label,
		&i.CreatedAt,
	)
	return i, err
}

const listPlanDays = `-- name: ListPlanDays :many
SELECT id, plan_id, day_number, label, created_at FROM plan_days
WHERE plan_id = $1
ORDER BY day_number ASC
`

func (q *Queries) ListPlanDays(ctx context.Context, planID pgtype.UUID) ([]PlanDay, error) {
	rows, err := q.db.Query(ctx, listPlanDays, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlanDay{}
	for rows.Next() {
		var i PlanDay
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.DayNumber,
			&i.Label,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlanDay = `-- name: UpdatePlanDay :one
UPDATE plan_days
SET label = $2
WHERE id = $1
RETURNING id, plan_id, day_number, label, created_at
`

type UpdatePlanDayParams struct {
	ID    pgtype.UUID `json:"id"`
	Label pgtype.Text `json:"label"`
}

func (q *Queries) UpdatePlanDay(ctx context.Context, arg UpdatePlanDayParams) (PlanDay, error) {
	row := q.db.QueryRow(ctx, updatePlanDay, arg.ID, arg.Label)
	var i PlanDay
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.DayNumber,
		&i.Label,
		&i.CreatedAt,
	)
	return i, err
}
