// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plan_exercises.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPlanExercise = `-- name: CreatePlanExercise :one
INSERT INTO plan_exercises (day_id, exercise_name, duration_minutes, description, calories_burn_estimate, display_order)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, day_id, exercise_name, duration_minutes, description, calories_burn_estimate, display_order, created_at
`

type CreatePlanExerciseParams struct {
	DayID                pgtype.UUID `json:"day_id"`
	ExerciseName         string      `json:"exercise_name"`
	DurationMinutes      int32       `json:"duration_minutes"`
	Description          pgtype.Text `json:"description"`
	CaloriesBurnEstimate pgtype.Int4 `json:"calories_burn_estimate"`
	DisplayOrder         int32       `json:"display_order"`
}

func (q *Queries) CreatePlanExercise(ctx context.Context, arg CreatePlanExerciseParams) (PlanExercise, error) {
	row := q.db.QueryRow(ctx, createPlanExercise,
		arg.DayID,
		arg.ExerciseName,
		arg.DurationMinutes,
		arg.Description,
		arg.CaloriesBurnEstimate,
		arg.DisplayOrder,
	)
	var i PlanExercise
	err := row.Scan(
		&i.ID,
		&i.DayID,
		&i.ExerciseName,
		&i.DurationMinutes,
		&i.Description,
		&i.CaloriesBurnEstimate,
		&i.DisplayOrder,
		&i.CreatedAt,
	)
	return i, err
}

const deletePlanExercise = `-- name: DeletePlanExercise :exec
DELETE FROM plan_exercises
WHERE id = $1 AND day_id = $2
`

type DeletePlanExerciseParams struct {
	ID    pgtype.UUID `json:"id"`
	DayID pgtype.UUID `json:"day_id"`
}

func (q *Queries) DeletePlanExercise(ctx context.Context, arg DeletePlanExerciseParams) error {
	_, err := q.db.Exec(ctx, deletePlanExercise, arg.ID, arg.DayID)
	return err
}

const getPlanExerciseByID = `-- name: GetPlanExerciseByID :one
SELECT id, day_id, exercise_name, duration_minutes, description, calories_burn_estimate, display_order, created_at FROM plan_exercises
WHERE id = $1 AND day_id = $2
`

type GetPlanExerciseByIDParams struct {
	ID    pgtype.UUID `json:"id"`
	DayID pgtype.UUID `json:"day_id"`
}

func (q *Queries) GetPlanExerciseByID(ctx context.Context, arg GetPlanExerciseByIDParams) (PlanExercise, error) {
	row := q.db.QueryRow(ctx, getPlanExerciseByID, arg.ID, arg.DayID)
	var i PlanExercise
	err := row.Scan(
		&i.ID,
		&i.DayID,
		&i.ExerciseName,
		&i.DurationMinutes,
		&i.Description,
		&i.CaloriesBurnEstimate,
		&i.DisplayOrder,
		&i.CreatedAt,
	)
	return i, err
}

const updatePlanExercise = `-- name: UpdatePlanExercise :one
UPDATE plan_exercises
SET exercise_name          = $2,
    duration_minutes       = $3,
    description            = $4,
    calories_burn_estimate = $5
WHERE id = $1
RETURNING id, day_id, exercise_name, duration_minutes, description, calories_burn_estimate, display_order, created_at
`

type UpdatePlanExerciseParams struct {
	ID                   pgtype.UUID `json:"id"`
	ExerciseName         string      `json:"exercise_name"`
	DurationMinutes      int32       `json:"duration_minutes"`
	Description          pgtype.Text `json:"description"`
	CaloriesBurnEstimate pgtype.Int4 `json:"calories_burn_estimate"`
}

func (q *Queries) UpdatePlanExercise(ctx context.Context, arg UpdatePlanExerciseParams) (PlanExercise, error) {
	row := q.db.QueryRow(ctx, updatePlanExercise,
		arg.ID,
		arg.ExerciseName,
		arg.DurationMinutes,
		arg.Description,
		arg.CaloriesBurnEstimate,
	)
	var i PlanExercise
	err := row.Scan(
		&i.ID,
		&i.DayID,
		&i.ExerciseName,
		&i.DurationMinutes,
		&i.Description,
		&i.CaloriesBurnEstimate,
		&i.DisplayOrder,
		&i.CreatedAt,
	)
	return i, err
}
