// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: push_subscriptions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deletePushSubscriptionByEndpoint = `-- name: DeletePushSubscriptionByEndpoint :exec
DELETE FROM push_subscriptions
WHERE client_id = $1 AND endpoint = $2
`

type DeletePushSubscriptionByEndpointParams struct {
	ClientID pgtype.UUID `json:"client_id"`
	Endpoint string      `json:"endpoint"`
}

func (q *Queries) DeletePushSubscriptionByEndpoint(ctx context.Context, arg DeletePushSubscriptionByEndpointParams) error {
	_, err := q.db.Exec(ctx, deletePushSubscriptionByEndpoint, arg.ClientID, arg.Endpoint)
	return err
}

const getPushSubscriptionsByClient = `-- name: GetPushSubscriptionsByClient :many
SELECT id, client_id, endpoint, p256dh_key, auth_key, user_agent, created_at, updated_at FROM push_subscriptions WHERE client_id = $1
`

func (q *Queries) GetPushSubscriptionsByClient(ctx context.Context, clientID pgtype.UUID) ([]PushSubscription, error) {
	rows, err := q.db.Query(ctx, getPushSubscriptionsByClient, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PushSubscription{}
	for rows.Next() {
		var i PushSubscription
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Endpoint,
			&i.P256dhKey,
			&i.AuthKey,
			&i.UserAgent,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertSentReminder = `-- name: InsertSentReminder :exec
INSERT INTO sent_reminders (client_id, dedup_key)
VALUES ($1, $2)
ON CONFLICT (client_id, dedup_key) DO NOTHING
`

type InsertSentReminderParams struct {
	ClientID pgtype.UUID `json:"client_id"`
	DedupKey string      `json:"dedup_key"`
}

func (q *Queries) InsertSentReminder(ctx context.Context, arg InsertSentReminderParams) error {
	_, err := q.db.Exec(ctx, insertSentReminder, arg.ClientID, arg.DedupKey)
	return err
}

const purgeSentRemindersOlderThan = `-- name: PurgeSentRemindersOlderThan :exec
DELETE FROM sent_reminders WHERE sent_at < $1
`

func (q *Queries) PurgeSentRemindersOlderThan(ctx context.Context, sentAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, purgeSentRemindersOlderThan, sentAt)
	return err
}

const reminderAlreadySent = `-- name: ReminderAlreadySent :one
SELECT EXISTS (
  SELECT 1 FROM sent_reminders WHERE client_id = $1 AND dedup_key = $2
) AS "exists"
`

type ReminderAlreadySentParams struct {
	ClientID pgtype.UUID `json:"client_id"`
	DedupKey string      `json:"dedup_key"`
}

func (q *Queries) ReminderAlreadySent(ctx context.Context, arg ReminderAlreadySentParams) (bool, error) {
	row := q.db.QueryRow(ctx, reminderAlreadySent, arg.ClientID, arg.DedupKey)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const upsertPushSubscription = `-- name: UpsertPushSubscription :one
INSERT INTO push_subscriptions (client_id, endpoint, p256dh_key, auth_key, user_agent)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (client_id, endpoint) DO UPDATE
  SET p256dh_key = EXCLUDED.p256dh_key,
      auth_key   = EXCLUDED.auth_key,
      user_agent = EXCLUDED.user_agent,
      updated_at = NOW()
RETURNING id, client_id, endpoint, p256dh_key, auth_key, user_agent, created_at, updated_at
`

type UpsertPushSubscriptionParams struct {
	ClientID  pgtype.UUID `json:"client_id"`
	Endpoint  string      `json:"endpoint"`
	P256dhKey string      `json:"p256dh_key"`
	AuthKey   string      `json:"auth_key"`
	UserAgent pgtype.Text `json:"user_agent"`
}

func (q *Queries) UpsertPushSubscription(ctx context.Context, arg UpsertPushSubscriptionParams) (PushSubscription, error) {
	row := q.db.QueryRow(ctx, upsertPushSubscription,
		arg.ClientID,
		arg.Endpoint,
		arg.P256dhKey,
		arg.AuthKey,
		arg.UserAgent,
	)
	var i PushSubscription
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Endpoint,
		&i.P256dhKey,
		&i.AuthKey,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
