// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateOTP(ctx context.Context, arg CreateOTPParams) (OtpCode, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpiredOTPs(ctx context.Context) error
	GetActiveOTPByMobile(ctx context.Context, mobile string) (OtpCode, error)
	GetClientsByNutritionistID(ctx context.Context, nutritionistID pgtype.UUID) ([]User, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetRefreshTokenByHashAny(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetUserByEmail(ctx context.Context, email pgtype.Text) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByMobile(ctx context.Context, mobile pgtype.Text) (User, error)
	IncrementOTPAttempts(ctx context.Context, id pgtype.UUID) error
	MarkOTPVerified(ctx context.Context, id pgtype.UUID) error
	RevokeRefreshToken(ctx context.Context, id pgtype.UUID) error
	RevokeTokenFamily(ctx context.Context, familyID pgtype.UUID) error
	RevokeUserTokens(ctx context.Context, userID pgtype.UUID) error
	UpdateUserActive(ctx context.Context, arg UpdateUserActiveParams) error
}

var _ Querier = (*Queries)(nil)
