// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    role, full_name, email, password_hash, mobile,
    date_of_birth, height_cm, gender, nutritionist_id, notes
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10
) RETURNING id, role, full_name, email, password_hash, mobile, date_of_birth, height_cm, gender, nutritionist_id, is_active, notes, created_at, updated_at
`

type CreateUserParams struct {
	Role           UserRole       `json:"role"`
	FullName       string         `json:"full_name"`
	Email          pgtype.Text    `json:"email"`
	PasswordHash   pgtype.Text    `json:"password_hash"`
	Mobile         pgtype.Text    `json:"mobile"`
	DateOfBirth    pgtype.Date    `json:"date_of_birth"`
	HeightCm       pgtype.Float4  `json:"height_cm"`
	Gender         NullGenderType `json:"gender"`
	NutritionistID pgtype.UUID    `json:"nutritionist_id"`
	Notes          pgtype.Text    `json:"notes"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Role,
		arg.FullName,
		arg.Email,
		arg.PasswordHash,
		arg.Mobile,
		arg.DateOfBirth,
		arg.HeightCm,
		arg.Gender,
		arg.NutritionistID,
		arg.Notes,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.FullName,
		&i.Email,
		&i.PasswordHash,
		&i.Mobile,
		&i.DateOfBirth,
		&i.HeightCm,
		&i.Gender,
		&i.NutritionistID,
		&i.IsActive,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClientsByNutritionistID = `-- name: GetClientsByNutritionistID :many
SELECT id, role, full_name, email, password_hash, mobile, date_of_birth, height_cm, gender, nutritionist_id, is_active, notes, created_at, updated_at FROM users
WHERE nutritionist_id = $1 AND role = 'client'
ORDER BY created_at DESC
`

func (q *Queries) GetClientsByNutritionistID(ctx context.Context, nutritionistID pgtype.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, getClientsByNutritionistID, nutritionistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.FullName,
			&i.Email,
			&i.PasswordHash,
			&i.Mobile,
			&i.DateOfBirth,
			&i.HeightCm,
			&i.Gender,
			&i.NutritionistID,
			&i.IsActive,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, role, full_name, email, password_hash, mobile, date_of_birth, height_cm, gender, nutritionist_id, is_active, notes, created_at, updated_at FROM users
WHERE email = $1 AND is_active = true
`

func (q *Queries) GetUserByEmail(ctx context.Context, email pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.FullName,
		&i.Email,
		&i.PasswordHash,
		&i.Mobile,
		&i.DateOfBirth,
		&i.HeightCm,
		&i.Gender,
		&i.NutritionistID,
		&i.IsActive,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, role, full_name, email, password_hash, mobile, date_of_birth, height_cm, gender, nutritionist_id, is_active, notes, created_at, updated_at FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.FullName,
		&i.Email,
		&i.PasswordHash,
		&i.Mobile,
		&i.DateOfBirth,
		&i.HeightCm,
		&i.Gender,
		&i.NutritionistID,
		&i.IsActive,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByMobile = `-- name: GetUserByMobile :one
SELECT id, role, full_name, email, password_hash, mobile, date_of_birth, height_cm, gender, nutritionist_id, is_active, notes, created_at, updated_at FROM users
WHERE mobile = $1 AND is_active = true
`

func (q *Queries) GetUserByMobile(ctx context.Context, mobile pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByMobile, mobile)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.FullName,
		&i.Email,
		&i.PasswordHash,
		&i.Mobile,
		&i.DateOfBirth,
		&i.HeightCm,
		&i.Gender,
		&i.NutritionistID,
		&i.IsActive,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserActive = `-- name: UpdateUserActive :exec
UPDATE users
SET is_active = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateUserActiveParams struct {
	ID       pgtype.UUID `json:"id"`
	IsActive bool        `json:"is_active"`
}

func (q *Queries) UpdateUserActive(ctx context.Context, arg UpdateUserActiveParams) error {
	_, err := q.db.Exec(ctx, updateUserActive, arg.ID, arg.IsActive)
	return err
}
