// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: water_logs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWaterLog = `-- name: CreateWaterLog :one
INSERT INTO water_logs (
    id, client_id, local_id, date, amount_ml, logged_time
) VALUES (
    gen_random_uuid(), $1, $2, $3, $4, $5
)
ON CONFLICT (local_id) DO NOTHING
RETURNING id, client_id, local_id, date, amount_ml, logged_time, created_at
`

type CreateWaterLogParams struct {
	ClientID   pgtype.UUID `json:"client_id"`
	LocalID    pgtype.UUID `json:"local_id"`
	Date       pgtype.Date `json:"date"`
	AmountMl   int32       `json:"amount_ml"`
	LoggedTime pgtype.Time `json:"logged_time"`
}

func (q *Queries) CreateWaterLog(ctx context.Context, arg CreateWaterLogParams) (WaterLog, error) {
	row := q.db.QueryRow(ctx, createWaterLog,
		arg.ClientID,
		arg.LocalID,
		arg.Date,
		arg.AmountMl,
		arg.LoggedTime,
	)
	var i WaterLog
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.LocalID,
		&i.Date,
		&i.AmountMl,
		&i.LoggedTime,
		&i.CreatedAt,
	)
	return i, err
}

const getWaterLogByLocalID = `-- name: GetWaterLogByLocalID :one
SELECT id, client_id, local_id, date, amount_ml, logged_time, created_at FROM water_logs
WHERE local_id = $1
  AND client_id = $2
`

type GetWaterLogByLocalIDParams struct {
	LocalID  pgtype.UUID `json:"local_id"`
	ClientID pgtype.UUID `json:"client_id"`
}

func (q *Queries) GetWaterLogByLocalID(ctx context.Context, arg GetWaterLogByLocalIDParams) (WaterLog, error) {
	row := q.db.QueryRow(ctx, getWaterLogByLocalID, arg.LocalID, arg.ClientID)
	var i WaterLog
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.LocalID,
		&i.Date,
		&i.AmountMl,
		&i.LoggedTime,
		&i.CreatedAt,
	)
	return i, err
}

const listWaterLogsByDate = `-- name: ListWaterLogsByDate :many
SELECT id, client_id, local_id, date, amount_ml, logged_time, created_at FROM water_logs
WHERE client_id = $1
  AND date = $2
ORDER BY logged_time ASC, created_at ASC
`

type ListWaterLogsByDateParams struct {
	ClientID pgtype.UUID `json:"client_id"`
	Date     pgtype.Date `json:"date"`
}

func (q *Queries) ListWaterLogsByDate(ctx context.Context, arg ListWaterLogsByDateParams) ([]WaterLog, error) {
	rows, err := q.db.Query(ctx, listWaterLogsByDate, arg.ClientID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WaterLog{}
	for rows.Next() {
		var i WaterLog
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.LocalID,
			&i.Date,
			&i.AmountMl,
			&i.LoggedTime,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWaterLogsByDateRange = `-- name: ListWaterLogsByDateRange :many
SELECT id, client_id, local_id, date, amount_ml, logged_time, created_at FROM water_logs
WHERE client_id = $1
  AND date BETWEEN $2 AND $3
ORDER BY date DESC, logged_time DESC, created_at DESC
`

type ListWaterLogsByDateRangeParams struct {
	ClientID pgtype.UUID `json:"client_id"`
	Date     pgtype.Date `json:"date"`
	Date_2   pgtype.Date `json:"date_2"`
}

func (q *Queries) ListWaterLogsByDateRange(ctx context.Context, arg ListWaterLogsByDateRangeParams) ([]WaterLog, error) {
	rows, err := q.db.Query(ctx, listWaterLogsByDateRange, arg.ClientID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WaterLog{}
	for rows.Next() {
		var i WaterLog
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.LocalID,
			&i.Date,
			&i.AmountMl,
			&i.LoggedTime,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWaterLogsForNutritionist = `-- name: ListWaterLogsForNutritionist :many
SELECT wl.id, wl.client_id, wl.local_id, wl.date, wl.amount_ml, wl.logged_time, wl.created_at
FROM water_logs wl
JOIN users u
  ON u.id = wl.client_id
 AND u.nutritionist_id = $1
WHERE wl.client_id = $2
  AND wl.date BETWEEN $3 AND $4
ORDER BY wl.date DESC, wl.logged_time DESC, wl.created_at DESC
`

type ListWaterLogsForNutritionistParams struct {
	NutritionistID pgtype.UUID `json:"nutritionist_id"`
	ClientID       pgtype.UUID `json:"client_id"`
	Date           pgtype.Date `json:"date"`
	Date_2         pgtype.Date `json:"date_2"`
}

func (q *Queries) ListWaterLogsForNutritionist(ctx context.Context, arg ListWaterLogsForNutritionistParams) ([]WaterLog, error) {
	rows, err := q.db.Query(ctx, listWaterLogsForNutritionist,
		arg.NutritionistID,
		arg.ClientID,
		arg.Date,
		arg.Date_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WaterLog{}
	for rows.Next() {
		var i WaterLog
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.LocalID,
			&i.Date,
			&i.AmountMl,
			&i.LoggedTime,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumWaterByDate = `-- name: SumWaterByDate :one
SELECT COALESCE(SUM(amount_ml), 0)::bigint AS total_ml
FROM water_logs
WHERE client_id = $1
  AND date = $2
`

type SumWaterByDateParams struct {
	ClientID pgtype.UUID `json:"client_id"`
	Date     pgtype.Date `json:"date"`
}

func (q *Queries) SumWaterByDate(ctx context.Context, arg SumWaterByDateParams) (int64, error) {
	row := q.db.QueryRow(ctx, sumWaterByDate, arg.ClientID, arg.Date)
	var total_ml int64
	err := row.Scan(&total_ml)
	return total_ml, err
}
