// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: day_prescribed_medications.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createDayPrescribedMedication = `-- name: CreateDayPrescribedMedication :one
INSERT INTO day_prescribed_medications (day_id, medication_id, dosage, frequency, times, instructions, start_date, end_date)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id, day_id, medication_id, dosage, frequency, times, instructions, start_date, end_date, created_at
`

type CreateDayPrescribedMedicationParams struct {
	DayID        uuid.UUID  `json:"day_id"`
	MedicationID uuid.UUID  `json:"medication_id"`
	Dosage       string     `json:"dosage"`
	Frequency    string     `json:"frequency"`
	Times        []string   `json:"times"`
	Instructions string     `json:"instructions"`
	StartDate    *time.Time `json:"start_date"`
	EndDate      *time.Time `json:"end_date"`
}

func (q *Queries) CreateDayPrescribedMedication(ctx context.Context, arg CreateDayPrescribedMedicationParams) (DayPrescribedMedication, error) {
	row := q.db.QueryRow(ctx, createDayPrescribedMedication,
		arg.DayID,
		arg.MedicationID,
		arg.Dosage,
		arg.Frequency,
		arg.Times,
		arg.Instructions,
		arg.StartDate,
		arg.EndDate,
	)
	var i DayPrescribedMedication
	err := row.Scan(
		&i.ID,
		&i.DayID,
		&i.MedicationID,
		&i.Dosage,
		&i.Frequency,
		&i.Times,
		&i.Instructions,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
	)
	return i, err
}

const getDayPrescribedMedication = `-- name: GetDayPrescribedMedication :one
SELECT id, day_id, medication_id, dosage, frequency, times, instructions, start_date, end_date, created_at FROM day_prescribed_medications WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDayPrescribedMedication(ctx context.Context, id uuid.UUID) (DayPrescribedMedication, error) {
	row := q.db.QueryRow(ctx, getDayPrescribedMedication, id)
	var i DayPrescribedMedication
	err := row.Scan(
		&i.ID,
		&i.DayID,
		&i.MedicationID,
		&i.Dosage,
		&i.Frequency,
		&i.Times,
		&i.Instructions,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
	)
	return i, err
}

// ListDayPrescribedMedicationsWithMedicationRow is the result row for the ListDayPrescribedMedicationsWithMedication query.
type ListDayPrescribedMedicationsWithMedicationRow struct {
	ID             uuid.UUID  `json:"id"`
	DayID          uuid.UUID  `json:"day_id"`
	MedicationID   uuid.UUID  `json:"medication_id"`
	Dosage         string     `json:"dosage"`
	Frequency      string     `json:"frequency"`
	Times          []string   `json:"times"`
	Instructions   string     `json:"instructions"`
	StartDate      *time.Time `json:"start_date"`
	EndDate        *time.Time `json:"end_date"`
	CreatedAt      time.Time  `json:"created_at"`
	MedicationName string     `json:"medication_name"`
	MedicationUnit string     `json:"medication_unit"`
}

const listDayPrescribedMedicationsWithMedication = `SELECT dpm.id, dpm.day_id, dpm.medication_id, dpm.dosage, dpm.frequency, dpm.times, dpm.instructions, dpm.start_date, dpm.end_date, dpm.created_at, m.name AS medication_name, m.unit AS medication_unit FROM day_prescribed_medications dpm JOIN medications m ON dpm.medication_id = m.id WHERE dpm.day_id = $1 ORDER BY dpm.created_at`

func (q *Queries) ListDayPrescribedMedicationsWithMedication(ctx context.Context, dayID uuid.UUID) ([]ListDayPrescribedMedicationsWithMedicationRow, error) {
	rows, err := q.db.Query(ctx, listDayPrescribedMedicationsWithMedication, dayID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDayPrescribedMedicationsWithMedicationRow
	for rows.Next() {
		var i ListDayPrescribedMedicationsWithMedicationRow
		if err := rows.Scan(
			&i.ID,
			&i.DayID,
			&i.MedicationID,
			&i.Dosage,
			&i.Frequency,
			&i.Times,
			&i.Instructions,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.MedicationName,
			&i.MedicationUnit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const deleteDayPrescribedMedication = `-- name: DeleteDayPrescribedMedication :exec
DELETE FROM day_prescribed_medications WHERE id = $1
`

func (q *Queries) DeleteDayPrescribedMedication(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDayPrescribedMedication, id)
	return err
}
