// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: diet_plan_days.sql

package db

import (
"context"

"github.com/google/uuid"
)

const createDietPlanDay = `-- name: CreateDietPlanDay :one
INSERT INTO diet_plan_days (plan_id, day_number) VALUES ($1, $2) RETURNING id, plan_id, day_number, created_at
`

type CreateDietPlanDayParams struct {
PlanID    uuid.UUID `json:"plan_id"`
DayNumber int32     `json:"day_number"`
}

func (q *Queries) CreateDietPlanDay(ctx context.Context, arg CreateDietPlanDayParams) (DietPlanDay, error) {
row := q.db.QueryRow(ctx, createDietPlanDay, arg.PlanID, arg.DayNumber)
var i DietPlanDay
err := row.Scan(
&i.ID,
&i.PlanID,
&i.DayNumber,
&i.CreatedAt,
)
return i, err
}

const deleteDietPlanDay = `-- name: DeleteDietPlanDay :exec
DELETE FROM diet_plan_days WHERE id = $1
`

func (q *Queries) DeleteDietPlanDay(ctx context.Context, id uuid.UUID) error {
_, err := q.db.Exec(ctx, deleteDietPlanDay, id)
return err
}

const getDietPlanDay = `-- name: GetDietPlanDay :one
SELECT id, plan_id, day_number, created_at FROM diet_plan_days WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDietPlanDay(ctx context.Context, id uuid.UUID) (DietPlanDay, error) {
row := q.db.QueryRow(ctx, getDietPlanDay, id)
var i DietPlanDay
err := row.Scan(
&i.ID,
&i.PlanID,
&i.DayNumber,
&i.CreatedAt,
)
return i, err
}

const listDietPlanDays = `-- name: ListDietPlanDays :many
SELECT id, plan_id, day_number, created_at FROM diet_plan_days WHERE plan_id = $1 ORDER BY day_number
`

func (q *Queries) ListDietPlanDays(ctx context.Context, planID uuid.UUID) ([]DietPlanDay, error) {
rows, err := q.db.Query(ctx, listDietPlanDays, planID)
if err != nil {
return nil, err
}
defer rows.Close()
items := []DietPlanDay{}
for rows.Next() {
var i DietPlanDay
if err := rows.Scan(
&i.ID,
&i.PlanID,
&i.DayNumber,
&i.CreatedAt,
); err != nil {
return nil, err
}
items = append(items, i)
}
if err := rows.Err(); err != nil {
return nil, err
}
return items, nil
}