// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: diet_meals.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDietMeal = `-- name: CreateDietMeal :one
INSERT INTO diet_meals (day_id, title, scheduled_time, display_order)
VALUES ($1, $2, $3, $4) RETURNING id, day_id, title, scheduled_time, display_order, created_at
`

type CreateDietMealParams struct {
	DayID         uuid.UUID   `json:"day_id"`
	Title         string      `json:"title"`
	ScheduledTime pgtype.Time `json:"scheduled_time"`
	DisplayOrder  int32       `json:"display_order"`
}

func (q *Queries) CreateDietMeal(ctx context.Context, arg CreateDietMealParams) (DietMeal, error) {
	row := q.db.QueryRow(ctx, createDietMeal,
		arg.DayID,
		arg.Title,
		arg.ScheduledTime,
		arg.DisplayOrder,
	)
	var i DietMeal
	err := row.Scan(
		&i.ID,
		&i.DayID,
		&i.Title,
		&i.ScheduledTime,
		&i.DisplayOrder,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDietMeal = `-- name: DeleteDietMeal :exec
DELETE FROM diet_meals WHERE id = $1
`

func (q *Queries) DeleteDietMeal(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDietMeal, id)
	return err
}

const getDietMeal = `-- name: GetDietMeal :one
SELECT id, day_id, title, scheduled_time, display_order, created_at FROM diet_meals WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDietMeal(ctx context.Context, id uuid.UUID) (DietMeal, error) {
	row := q.db.QueryRow(ctx, getDietMeal, id)
	var i DietMeal
	err := row.Scan(
		&i.ID,
		&i.DayID,
		&i.Title,
		&i.ScheduledTime,
		&i.DisplayOrder,
		&i.CreatedAt,
	)
	return i, err
}

const listDietMeals = `-- name: ListDietMeals :many
SELECT id, day_id, title, scheduled_time, display_order, created_at FROM diet_meals WHERE day_id = $1 ORDER BY display_order, scheduled_time
`

func (q *Queries) ListDietMeals(ctx context.Context, dayID uuid.UUID) ([]DietMeal, error) {
	rows, err := q.db.Query(ctx, listDietMeals, dayID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DietMeal{}
	for rows.Next() {
		var i DietMeal
		if err := rows.Scan(
			&i.ID,
			&i.DayID,
			&i.Title,
			&i.ScheduledTime,
			&i.DisplayOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
