// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: diet_plans.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const archiveActivePlanForClient = `-- name: ArchiveActivePlanForClient :exec
UPDATE diet_plans
SET status = 'archived', updated_at = NOW()
WHERE client_id = $1 AND status = 'active'
`

func (q *Queries) ArchiveActivePlanForClient(ctx context.Context, clientID uuid.UUID) error {
	_, err := q.db.Exec(ctx, archiveActivePlanForClient, clientID)
	return err
}

const countPlansByClientID = `-- name: CountPlansByClientID :one
SELECT COUNT(*) FROM diet_plans WHERE client_id = $1
`

func (q *Queries) CountPlansByClientID(ctx context.Context, clientID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPlansByClientID, clientID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDietPlan = `-- name: CreateDietPlan :one
INSERT INTO diet_plans (client_id, nutritionist_id, title, start_date, end_date, notes, daily_water_target_ml, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, 'active')
RETURNING id, client_id, nutritionist_id, title, start_date, end_date, notes, daily_water_target_ml, status, created_at, updated_at
`

type CreateDietPlanParams struct {
	ClientID           uuid.UUID `json:"client_id"`
	NutritionistID     uuid.UUID `json:"nutritionist_id"`
	Title              string    `json:"title"`
	StartDate          time.Time `json:"start_date"`
	EndDate            time.Time `json:"end_date"`
	Notes              string    `json:"notes"`
	DailyWaterTargetMl int32     `json:"daily_water_target_ml"`
}

func (q *Queries) CreateDietPlan(ctx context.Context, arg CreateDietPlanParams) (DietPlan, error) {
	row := q.db.QueryRow(ctx, createDietPlan,
		arg.ClientID,
		arg.NutritionistID,
		arg.Title,
		arg.StartDate,
		arg.EndDate,
		arg.Notes,
		arg.DailyWaterTargetMl,
	)
	var i DietPlan
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.NutritionistID,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
		&i.Notes,
		&i.DailyWaterTargetMl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDietPlan = `-- name: DeleteDietPlan :exec
DELETE FROM diet_plans WHERE id = $1
`

func (q *Queries) DeleteDietPlan(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDietPlan, id)
	return err
}

const getActivePlanByClientID = `-- name: GetActivePlanByClientID :one
SELECT id, client_id, nutritionist_id, title, start_date, end_date, notes, daily_water_target_ml, status, created_at, updated_at FROM diet_plans WHERE client_id = $1 AND status = 'active' LIMIT 1
`

func (q *Queries) GetActivePlanByClientID(ctx context.Context, clientID uuid.UUID) (DietPlan, error) {
	row := q.db.QueryRow(ctx, getActivePlanByClientID, clientID)
	var i DietPlan
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.NutritionistID,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
		&i.Notes,
		&i.DailyWaterTargetMl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDietPlanByID = `-- name: GetDietPlanByID :one
SELECT id, client_id, nutritionist_id, title, start_date, end_date, notes, daily_water_target_ml, status, created_at, updated_at FROM diet_plans WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDietPlanByID(ctx context.Context, id uuid.UUID) (DietPlan, error) {
	row := q.db.QueryRow(ctx, getDietPlanByID, id)
	var i DietPlan
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.NutritionistID,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
		&i.Notes,
		&i.DailyWaterTargetMl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPlansByClientID = `-- name: ListPlansByClientID :many
SELECT id, client_id, nutritionist_id, title, start_date, end_date, notes, daily_water_target_ml, status, created_at, updated_at FROM diet_plans WHERE client_id = $1
ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListPlansByClientIDParams struct {
	ClientID uuid.UUID `json:"client_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListPlansByClientID(ctx context.Context, arg ListPlansByClientIDParams) ([]DietPlan, error) {
	rows, err := q.db.Query(ctx, listPlansByClientID, arg.ClientID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DietPlan{}
	for rows.Next() {
		var i DietPlan
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.NutritionistID,
			&i.Title,
			&i.StartDate,
			&i.EndDate,
			&i.Notes,
			&i.DailyWaterTargetMl,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDietPlan = `-- name: UpdateDietPlan :one
UPDATE diet_plans
SET title = $2, notes = $3, daily_water_target_ml = $4, updated_at = NOW()
WHERE id = $1 RETURNING id, client_id, nutritionist_id, title, start_date, end_date, notes, daily_water_target_ml, status, created_at, updated_at
`

type UpdateDietPlanParams struct {
	ID                 uuid.UUID `json:"id"`
	Title              string    `json:"title"`
	Notes              string    `json:"notes"`
	DailyWaterTargetMl int32     `json:"daily_water_target_ml"`
}

func (q *Queries) UpdateDietPlan(ctx context.Context, arg UpdateDietPlanParams) (DietPlan, error) {
	row := q.db.QueryRow(ctx, updateDietPlan,
		arg.ID,
		arg.Title,
		arg.Notes,
		arg.DailyWaterTargetMl,
	)
	var i DietPlan
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.NutritionistID,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
		&i.Notes,
		&i.DailyWaterTargetMl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
