// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: exercise_recommendations.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createExerciseRecommendation = `-- name: CreateExerciseRecommendation :one
INSERT INTO exercise_recommendations (day_id, exercise_name, duration_minutes, description, calories_burn_estimate)
VALUES ($1, $2, $3, $4, $5) RETURNING id, day_id, exercise_name, duration_minutes, description, calories_burn_estimate, created_at
`

type CreateExerciseRecommendationParams struct {
	DayID                uuid.UUID `json:"day_id"`
	ExerciseName         string    `json:"exercise_name"`
	DurationMinutes      int32     `json:"duration_minutes"`
	Description          string    `json:"description"`
	CaloriesBurnEstimate int32     `json:"calories_burn_estimate"`
}

func (q *Queries) CreateExerciseRecommendation(ctx context.Context, arg CreateExerciseRecommendationParams) (ExerciseRecommendation, error) {
	row := q.db.QueryRow(ctx, createExerciseRecommendation,
		arg.DayID,
		arg.ExerciseName,
		arg.DurationMinutes,
		arg.Description,
		arg.CaloriesBurnEstimate,
	)
	var i ExerciseRecommendation
	err := row.Scan(
		&i.ID,
		&i.DayID,
		&i.ExerciseName,
		&i.DurationMinutes,
		&i.Description,
		&i.CaloriesBurnEstimate,
		&i.CreatedAt,
	)
	return i, err
}

const getExerciseRecommendation = `-- name: GetExerciseRecommendation :one
SELECT id, day_id, exercise_name, duration_minutes, description, calories_burn_estimate, created_at FROM exercise_recommendations WHERE id = $1 LIMIT 1
`

func (q *Queries) GetExerciseRecommendation(ctx context.Context, id uuid.UUID) (ExerciseRecommendation, error) {
	row := q.db.QueryRow(ctx, getExerciseRecommendation, id)
	var i ExerciseRecommendation
	err := row.Scan(
		&i.ID,
		&i.DayID,
		&i.ExerciseName,
		&i.DurationMinutes,
		&i.Description,
		&i.CaloriesBurnEstimate,
		&i.CreatedAt,
	)
	return i, err
}

const listExerciseRecommendations = `-- name: ListExerciseRecommendations :many
SELECT id, day_id, exercise_name, duration_minutes, description, calories_burn_estimate, created_at FROM exercise_recommendations WHERE day_id = $1 ORDER BY created_at
`

func (q *Queries) ListExerciseRecommendations(ctx context.Context, dayID uuid.UUID) ([]ExerciseRecommendation, error) {
	rows, err := q.db.Query(ctx, listExerciseRecommendations, dayID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExerciseRecommendation{}
	for rows.Next() {
		var i ExerciseRecommendation
		if err := rows.Scan(
			&i.ID,
			&i.DayID,
			&i.ExerciseName,
			&i.DurationMinutes,
			&i.Description,
			&i.CaloriesBurnEstimate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteExerciseRecommendation = `-- name: DeleteExerciseRecommendation :exec
DELETE FROM exercise_recommendations WHERE id = $1
`

func (q *Queries) DeleteExerciseRecommendation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteExerciseRecommendation, id)
	return err
}

