// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: food_categories.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createFoodCategory = `-- name: CreateFoodCategory :one
INSERT INTO food_categories (name) VALUES ($1) RETURNING id, name, created_at
`

func (q *Queries) CreateFoodCategory(ctx context.Context, name string) (FoodCategory, error) {
	row := q.db.QueryRow(ctx, createFoodCategory, name)
	var i FoodCategory
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const deleteFoodCategory = `-- name: DeleteFoodCategory :exec
DELETE FROM food_categories WHERE id = $1
`

func (q *Queries) DeleteFoodCategory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteFoodCategory, id)
	return err
}

const getFoodCategoryByID = `-- name: GetFoodCategoryByID :one
SELECT id, name, created_at FROM food_categories WHERE id = $1 LIMIT 1
`

func (q *Queries) GetFoodCategoryByID(ctx context.Context, id uuid.UUID) (FoodCategory, error) {
	row := q.db.QueryRow(ctx, getFoodCategoryByID, id)
	var i FoodCategory
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getFoodCategoryByName = `-- name: GetFoodCategoryByName :one
SELECT id, name, created_at FROM food_categories WHERE name = $1 LIMIT 1
`

func (q *Queries) GetFoodCategoryByName(ctx context.Context, name string) (FoodCategory, error) {
	row := q.db.QueryRow(ctx, getFoodCategoryByName, name)
	var i FoodCategory
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const listFoodCategories = `-- name: ListFoodCategories :many
SELECT id, name, created_at FROM food_categories ORDER BY name
`

func (q *Queries) ListFoodCategories(ctx context.Context) ([]FoodCategory, error) {
	rows, err := q.db.Query(ctx, listFoodCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FoodCategory{}
	for rows.Next() {
		var i FoodCategory
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
