// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: foods.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addFoodCategory = `-- name: AddFoodCategory :exec
INSERT INTO food_category_mappings (food_id, category_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AddFoodCategoryParams struct {
	FoodID     uuid.UUID `json:"food_id"`
	CategoryID uuid.UUID `json:"category_id"`
}

func (q *Queries) AddFoodCategory(ctx context.Context, arg AddFoodCategoryParams) error {
	_, err := q.db.Exec(ctx, addFoodCategory, arg.FoodID, arg.CategoryID)
	return err
}

const countSearchFoods = `-- name: CountSearchFoods :one
SELECT COUNT(*) FROM foods
WHERE is_active = true
  AND (
    $1::text = ''
    OR similarity(name_normalized, $1::text) > 0.15
    OR name_normalized ILIKE '%' || $1::text || '%'
  )
`

func (q *Queries) CountSearchFoods(ctx context.Context, query string) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchFoods, query)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFood = `-- name: CreateFood :one
INSERT INTO foods (name, name_normalized, unit, calories, protein, carbohydrate, fat, fiber, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, name, name_normalized, unit, calories, protein, carbohydrate, fat, fiber, created_by, is_active, created_at, updated_at
`

type CreateFoodParams struct {
	Name           string         `json:"name"`
	NameNormalized string         `json:"name_normalized"`
	Unit           string         `json:"unit"`
	Calories       pgtype.Numeric `json:"calories"`
	Protein        pgtype.Numeric `json:"protein"`
	Carbohydrate   pgtype.Numeric `json:"carbohydrate"`
	Fat            pgtype.Numeric `json:"fat"`
	Fiber          pgtype.Numeric `json:"fiber"`
	CreatedBy      pgtype.UUID    `json:"created_by"`
}

func (q *Queries) CreateFood(ctx context.Context, arg CreateFoodParams) (Food, error) {
	row := q.db.QueryRow(ctx, createFood,
		arg.Name,
		arg.NameNormalized,
		arg.Unit,
		arg.Calories,
		arg.Protein,
		arg.Carbohydrate,
		arg.Fat,
		arg.Fiber,
		arg.CreatedBy,
	)
	var i Food
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameNormalized,
		&i.Unit,
		&i.Calories,
		&i.Protein,
		&i.Carbohydrate,
		&i.Fat,
		&i.Fiber,
		&i.CreatedBy,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateFood = `-- name: DeactivateFood :exec
UPDATE foods SET is_active = false, updated_at = NOW() WHERE id = $1
`

func (q *Queries) DeactivateFood(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deactivateFood, id)
	return err
}

const deleteFood = `-- name: DeleteFood :exec
DELETE FROM foods WHERE id = $1
`

func (q *Queries) DeleteFood(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteFood, id)
	return err
}

const getFoodByID = `-- name: GetFoodByID :one
SELECT id, name, name_normalized, unit, calories, protein, carbohydrate, fat, fiber, created_by, is_active, created_at, updated_at FROM foods WHERE id = $1 LIMIT 1
`

func (q *Queries) GetFoodByID(ctx context.Context, id uuid.UUID) (Food, error) {
	row := q.db.QueryRow(ctx, getFoodByID, id)
	var i Food
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameNormalized,
		&i.Unit,
		&i.Calories,
		&i.Protein,
		&i.Carbohydrate,
		&i.Fat,
		&i.Fiber,
		&i.CreatedBy,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFoodCategories = `-- name: GetFoodCategories :many
SELECT fc.id, fc.name, fc.created_at
FROM food_categories fc
JOIN food_category_mappings fcm ON fc.id = fcm.category_id
WHERE fcm.food_id = $1
`

func (q *Queries) GetFoodCategories(ctx context.Context, foodID uuid.UUID) ([]FoodCategory, error) {
	rows, err := q.db.Query(ctx, getFoodCategories, foodID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FoodCategory{}
	for rows.Next() {
		var i FoodCategory
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFoodCategories = `-- name: RemoveFoodCategories :exec
DELETE FROM food_category_mappings WHERE food_id = $1
`

func (q *Queries) RemoveFoodCategories(ctx context.Context, foodID uuid.UUID) error {
	_, err := q.db.Exec(ctx, removeFoodCategories, foodID)
	return err
}

const searchFoods = `-- name: SearchFoods :many
SELECT id, name, name_normalized, unit, calories, protein, carbohydrate, fat, fiber, created_by, is_active, created_at, updated_at FROM foods
WHERE is_active = true
  AND (
    $1::text = ''
    OR similarity(name_normalized, $1::text) > 0.15
    OR name_normalized ILIKE '%' || $1::text || '%'
  )
ORDER BY
  CASE WHEN $1::text = '' THEN 0.0 ELSE -similarity(name_normalized, $1::text) END,
  created_at DESC
LIMIT $3::int OFFSET $2::int
`

type SearchFoodsParams struct {
	Query string `json:"query"`
	Off   int32  `json:"off"`
	Lim   int32  `json:"lim"`
}

func (q *Queries) SearchFoods(ctx context.Context, arg SearchFoodsParams) ([]Food, error) {
	rows, err := q.db.Query(ctx, searchFoods, arg.Query, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Food{}
	for rows.Next() {
		var i Food
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameNormalized,
			&i.Unit,
			&i.Calories,
			&i.Protein,
			&i.Carbohydrate,
			&i.Fat,
			&i.Fiber,
			&i.CreatedBy,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFood = `-- name: UpdateFood :one
UPDATE foods
SET name            = $2,
    name_normalized = $3,
    unit            = $4,
    calories        = $5,
    protein         = $6,
    carbohydrate    = $7,
    fat             = $8,
    fiber           = $9,
    updated_at      = NOW()
WHERE id = $1
RETURNING id, name, name_normalized, unit, calories, protein, carbohydrate, fat, fiber, created_by, is_active, created_at, updated_at
`

type UpdateFoodParams struct {
	ID             uuid.UUID      `json:"id"`
	Name           string         `json:"name"`
	NameNormalized string         `json:"name_normalized"`
	Unit           string         `json:"unit"`
	Calories       pgtype.Numeric `json:"calories"`
	Protein        pgtype.Numeric `json:"protein"`
	Carbohydrate   pgtype.Numeric `json:"carbohydrate"`
	Fat            pgtype.Numeric `json:"fat"`
	Fiber          pgtype.Numeric `json:"fiber"`
}

func (q *Queries) UpdateFood(ctx context.Context, arg UpdateFoodParams) (Food, error) {
	row := q.db.QueryRow(ctx, updateFood,
		arg.ID,
		arg.Name,
		arg.NameNormalized,
		arg.Unit,
		arg.Calories,
		arg.Protein,
		arg.Carbohydrate,
		arg.Fat,
		arg.Fiber,
	)
	var i Food
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameNormalized,
		&i.Unit,
		&i.Calories,
		&i.Protein,
		&i.Carbohydrate,
		&i.Fat,
		&i.Fiber,
		&i.CreatedBy,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
