// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: health.sql

package db

import (
	"context"
)

const healthCheck = `-- name: HealthCheck :one
SELECT 1::integer AS result
`

func (q *Queries) HealthCheck(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, healthCheck)
	var result int32
	err := row.Scan(&result)
	return result, err
}
