// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: meal_options.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createMealOption = `-- name: CreateMealOption :one
INSERT INTO meal_options (meal_id, option_number) VALUES ($1, $2) RETURNING id, meal_id, option_number, created_at
`

type CreateMealOptionParams struct {
	MealID       uuid.UUID `json:"meal_id"`
	OptionNumber int32     `json:"option_number"`
}

func (q *Queries) CreateMealOption(ctx context.Context, arg CreateMealOptionParams) (MealOption, error) {
	row := q.db.QueryRow(ctx, createMealOption, arg.MealID, arg.OptionNumber)
	var i MealOption
	err := row.Scan(
		&i.ID,
		&i.MealID,
		&i.OptionNumber,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMealOption = `-- name: DeleteMealOption :exec
DELETE FROM meal_options WHERE id = $1
`

func (q *Queries) DeleteMealOption(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMealOption, id)
	return err
}

const getMealOption = `-- name: GetMealOption :one
SELECT id, meal_id, option_number, created_at FROM meal_options WHERE id = $1 LIMIT 1
`

func (q *Queries) GetMealOption(ctx context.Context, id uuid.UUID) (MealOption, error) {
	row := q.db.QueryRow(ctx, getMealOption, id)
	var i MealOption
	err := row.Scan(
		&i.ID,
		&i.MealID,
		&i.OptionNumber,
		&i.CreatedAt,
	)
	return i, err
}

const listMealOptions = `-- name: ListMealOptions :many
SELECT id, meal_id, option_number, created_at FROM meal_options WHERE meal_id = $1 ORDER BY option_number
`

func (q *Queries) ListMealOptions(ctx context.Context, mealID uuid.UUID) ([]MealOption, error) {
	rows, err := q.db.Query(ctx, listMealOptions, mealID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MealOption{}
	for rows.Next() {
		var i MealOption
		if err := rows.Scan(
			&i.ID,
			&i.MealID,
			&i.OptionNumber,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
