// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: meal_option_items.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMealOptionItem = `-- name: CreateMealOptionItem :one
INSERT INTO meal_option_items (option_id, food_id, quantity, unit, notes)
VALUES ($1, $2, $3, $4, $5) RETURNING id, option_id, food_id, quantity, unit, notes, created_at
`

type CreateMealOptionItemParams struct {
	OptionID uuid.UUID      `json:"option_id"`
	FoodID   uuid.UUID      `json:"food_id"`
	Quantity pgtype.Numeric `json:"quantity"`
	Unit     string         `json:"unit"`
	Notes    string         `json:"notes"`
}

func (q *Queries) CreateMealOptionItem(ctx context.Context, arg CreateMealOptionItemParams) (MealOptionItem, error) {
	row := q.db.QueryRow(ctx, createMealOptionItem,
		arg.OptionID,
		arg.FoodID,
		arg.Quantity,
		arg.Unit,
		arg.Notes,
	)
	var i MealOptionItem
	err := row.Scan(
		&i.ID,
		&i.OptionID,
		&i.FoodID,
		&i.Quantity,
		&i.Unit,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMealOptionItem = `-- name: DeleteMealOptionItem :exec
DELETE FROM meal_option_items WHERE id = $1
`

func (q *Queries) DeleteMealOptionItem(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMealOptionItem, id)
	return err
}

const deleteMealOptionItemsByOption = `-- name: DeleteMealOptionItemsByOption :exec
DELETE FROM meal_option_items WHERE option_id = $1
`

func (q *Queries) DeleteMealOptionItemsByOption(ctx context.Context, optionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMealOptionItemsByOption, optionID)
	return err
}

const getMealOptionItem = `-- name: GetMealOptionItem :one
SELECT id, option_id, food_id, quantity, unit, notes, created_at FROM meal_option_items WHERE id = $1 LIMIT 1
`

func (q *Queries) GetMealOptionItem(ctx context.Context, id uuid.UUID) (MealOptionItem, error) {
	row := q.db.QueryRow(ctx, getMealOptionItem, id)
	var i MealOptionItem
	err := row.Scan(
		&i.ID,
		&i.OptionID,
		&i.FoodID,
		&i.Quantity,
		&i.Unit,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const listMealOptionItems = `-- name: ListMealOptionItems :many
SELECT id, option_id, food_id, quantity, unit, notes, created_at FROM meal_option_items WHERE option_id = $1 ORDER BY created_at
`

func (q *Queries) ListMealOptionItems(ctx context.Context, optionID uuid.UUID) ([]MealOptionItem, error) {
	rows, err := q.db.Query(ctx, listMealOptionItems, optionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MealOptionItem{}
	for rows.Next() {
		var i MealOptionItem
		if err := rows.Scan(
			&i.ID,
			&i.OptionID,
			&i.FoodID,
			&i.Quantity,
			&i.Unit,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

// ListMealOptionItemsWithFoodRow is the result row for the ListMealOptionItemsWithFood query.
type ListMealOptionItemsWithFoodRow struct {
	ID               uuid.UUID      `json:"id"`
	OptionID         uuid.UUID      `json:"option_id"`
	FoodID           uuid.UUID      `json:"food_id"`
	Quantity         pgtype.Numeric `json:"quantity"`
	Unit             string         `json:"unit"`
	Notes            string         `json:"notes"`
	CreatedAt        time.Time      `json:"created_at"`
	FoodName         string         `json:"food_name"`
	FoodUnit         string         `json:"food_unit"`
	FoodCalories     pgtype.Numeric `json:"food_calories"`
	FoodProtein      pgtype.Numeric `json:"food_protein"`
	FoodCarbohydrate pgtype.Numeric `json:"food_carbohydrate"`
	FoodFat          pgtype.Numeric `json:"food_fat"`
	FoodFiber        pgtype.Numeric `json:"food_fiber"`
}

const listMealOptionItemsWithFood = `SELECT moi.id, moi.option_id, moi.food_id, moi.quantity, moi.unit, moi.notes, moi.created_at, f.name AS food_name, f.unit AS food_unit, f.calories AS food_calories, f.protein AS food_protein, f.carbohydrate AS food_carbohydrate, f.fat AS food_fat, f.fiber AS food_fiber FROM meal_option_items moi JOIN foods f ON moi.food_id = f.id WHERE moi.option_id = $1 ORDER BY moi.created_at`

// ListMealOptionItemsWithFood returns items for an option joined with food data.
func (q *Queries) ListMealOptionItemsWithFood(ctx context.Context, optionID uuid.UUID) ([]ListMealOptionItemsWithFoodRow, error) {
	rows, err := q.db.Query(ctx, listMealOptionItemsWithFood, optionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMealOptionItemsWithFoodRow
	for rows.Next() {
		var i ListMealOptionItemsWithFoodRow
		if err := rows.Scan(
			&i.ID, &i.OptionID, &i.FoodID, &i.Quantity, &i.Unit, &i.Notes, &i.CreatedAt,
			&i.FoodName, &i.FoodUnit, &i.FoodCalories, &i.FoodProtein, &i.FoodCarbohydrate, &i.FoodFat, &i.FoodFiber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

