// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: medications.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMedication = `-- name: CreateMedication :one
INSERT INTO medications (name, name_normalized, description, unit, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, name_normalized, description, unit, created_by, is_active, created_at, updated_at
`

type CreateMedicationParams struct {
	Name           string      `json:"name"`
	NameNormalized string      `json:"name_normalized"`
	Description    string      `json:"description"`
	Unit           string      `json:"unit"`
	CreatedBy      pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateMedication(ctx context.Context, arg CreateMedicationParams) (Medication, error) {
	row := q.db.QueryRow(ctx, createMedication,
		arg.Name,
		arg.NameNormalized,
		arg.Description,
		arg.Unit,
		arg.CreatedBy,
	)
	var i Medication
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameNormalized,
		&i.Description,
		&i.Unit,
		&i.CreatedBy,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMedicationByID = `-- name: GetMedicationByID :one
SELECT id, name, name_normalized, description, unit, created_by, is_active, created_at, updated_at FROM medications WHERE id = $1 LIMIT 1
`

func (q *Queries) GetMedicationByID(ctx context.Context, id uuid.UUID) (Medication, error) {
	row := q.db.QueryRow(ctx, getMedicationByID, id)
	var i Medication
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameNormalized,
		&i.Description,
		&i.Unit,
		&i.CreatedBy,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const searchMedications = `-- name: SearchMedications :many
SELECT id, name, name_normalized, description, unit, created_by, is_active, created_at, updated_at FROM medications
WHERE is_active = true
  AND (
    $1::text = ''
    OR similarity(name_normalized, $1::text) > 0.15
    OR name_normalized ILIKE '%' || $1::text || '%'
  )
ORDER BY
  CASE WHEN $1::text = '' THEN 0.0 ELSE -similarity(name_normalized, $1::text) END,
  created_at DESC
LIMIT $2::int OFFSET $3::int
`

type SearchMedicationsParams struct {
	Query string `json:"query"`
	Lim   int32  `json:"lim"`
	Off   int32  `json:"off"`
}

func (q *Queries) SearchMedications(ctx context.Context, arg SearchMedicationsParams) ([]Medication, error) {
	rows, err := q.db.Query(ctx, searchMedications, arg.Query, arg.Lim, arg.Off)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Medication{}
	for rows.Next() {
		var i Medication
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameNormalized,
			&i.Description,
			&i.Unit,
			&i.CreatedBy,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countSearchMedications = `-- name: CountSearchMedications :one
SELECT COUNT(*) FROM medications
WHERE is_active = true
  AND (
    $1::text = ''
    OR similarity(name_normalized, $1::text) > 0.15
    OR name_normalized ILIKE '%' || $1::text || '%'
  )
`

func (q *Queries) CountSearchMedications(ctx context.Context, query string) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchMedications, query)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateMedication = `-- name: UpdateMedication :one
UPDATE medications
SET name            = $2,
    name_normalized = $3,
    description     = $4,
    unit            = $5,
    updated_at      = NOW()
WHERE id = $1
RETURNING id, name, name_normalized, description, unit, created_by, is_active, created_at, updated_at
`

type UpdateMedicationParams struct {
	ID             uuid.UUID `json:"id"`
	Name           string    `json:"name"`
	NameNormalized string    `json:"name_normalized"`
	Description    string    `json:"description"`
	Unit           string    `json:"unit"`
}

func (q *Queries) UpdateMedication(ctx context.Context, arg UpdateMedicationParams) (Medication, error) {
	row := q.db.QueryRow(ctx, updateMedication,
		arg.ID,
		arg.Name,
		arg.NameNormalized,
		arg.Description,
		arg.Unit,
	)
	var i Medication
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameNormalized,
		&i.Description,
		&i.Unit,
		&i.CreatedBy,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateMedication = `-- name: DeactivateMedication :exec
UPDATE medications SET is_active = false, updated_at = NOW() WHERE id = $1
`

func (q *Queries) DeactivateMedication(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deactivateMedication, id)
	return err
}

const deleteMedication = `-- name: DeleteMedication :exec
DELETE FROM medications WHERE id = $1
`

func (q *Queries) DeleteMedication(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMedication, id)
	return err
}
