// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID             uuid.UUID      `json:"id"`
	Role           string         `json:"role"`
	Mobile         string         `json:"mobile"`
	Email          *string        `json:"email"`
	PasswordHash   *string        `json:"password_hash"`
	FirstName      string         `json:"first_name"`
	LastName       string         `json:"last_name"`
	Gender         *string        `json:"gender"`
	BirthDate      pgtype.Date    `json:"birth_date"`
	Height         pgtype.Numeric `json:"height"`
	Weight         pgtype.Numeric `json:"weight"`
	AvatarUrl      *string        `json:"avatar_url"`
	IsActive       bool           `json:"is_active"`
	NutritionistID pgtype.UUID    `json:"nutritionist_id"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}
