// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
"time"

"github.com/google/uuid"
"github.com/jackc/pgx/v5/pgtype"
)

type DietPlanStatus string

const (
DietPlanStatusActive   DietPlanStatus = "active"
DietPlanStatusArchived DietPlanStatus = "archived"
DietPlanStatusDraft    DietPlanStatus = "draft"
)

type DietPlan struct {
ID                 uuid.UUID      `json:"id"`
ClientID           uuid.UUID      `json:"client_id"`
NutritionistID     uuid.UUID      `json:"nutritionist_id"`
Title              string         `json:"title"`
StartDate          time.Time      `json:"start_date"`
EndDate            time.Time      `json:"end_date"`
Notes              string         `json:"notes"`
DailyWaterTargetMl int32          `json:"daily_water_target_ml"`
Status             DietPlanStatus `json:"status"`
CreatedAt          time.Time      `json:"created_at"`
UpdatedAt          time.Time      `json:"updated_at"`
}

type DietPlanDay struct {
ID        uuid.UUID `json:"id"`
PlanID    uuid.UUID `json:"plan_id"`
DayNumber int32     `json:"day_number"`
CreatedAt time.Time `json:"created_at"`
}

type DietMeal struct {
ID            uuid.UUID   `json:"id"`
DayID         uuid.UUID   `json:"day_id"`
Title         string      `json:"title"`
ScheduledTime pgtype.Time `json:"scheduled_time"`
DisplayOrder  int32       `json:"display_order"`
CreatedAt     time.Time   `json:"created_at"`
}

type Food struct {
ID             uuid.UUID      `json:"id"`
Name           string         `json:"name"`
NameNormalized string         `json:"name_normalized"`
Unit           string         `json:"unit"`
Calories       pgtype.Numeric `json:"calories"`
Protein        pgtype.Numeric `json:"protein"`
Carbohydrate   pgtype.Numeric `json:"carbohydrate"`
Fat            pgtype.Numeric `json:"fat"`
Fiber          pgtype.Numeric `json:"fiber"`
CreatedBy      pgtype.UUID    `json:"created_by"`
IsActive       bool           `json:"is_active"`
CreatedAt      time.Time      `json:"created_at"`
UpdatedAt      time.Time      `json:"updated_at"`
}

type FoodCategory struct {
ID        uuid.UUID `json:"id"`
Name      string    `json:"name"`
CreatedAt time.Time `json:"created_at"`
}

type FoodCategoryMapping struct {
FoodID     uuid.UUID `json:"food_id"`
CategoryID uuid.UUID `json:"category_id"`
}

type MealOption struct {
ID           uuid.UUID `json:"id"`
MealID       uuid.UUID `json:"meal_id"`
OptionNumber int32     `json:"option_number"`
CreatedAt    time.Time `json:"created_at"`
}

type MealOptionItem struct {
ID        uuid.UUID      `json:"id"`
OptionID  uuid.UUID      `json:"option_id"`
FoodID    uuid.UUID      `json:"food_id"`
Quantity  pgtype.Numeric `json:"quantity"`
Unit      string         `json:"unit"`
Notes     string         `json:"notes"`
CreatedAt time.Time      `json:"created_at"`
}

type Medication struct {
ID             uuid.UUID   `json:"id"`
Name           string      `json:"name"`
NameNormalized string      `json:"name_normalized"`
Description    string      `json:"description"`
Unit           string      `json:"unit"`
CreatedBy      pgtype.UUID `json:"created_by"`
IsActive       bool        `json:"is_active"`
CreatedAt      time.Time   `json:"created_at"`
UpdatedAt      time.Time   `json:"updated_at"`
}

type ExerciseRecommendation struct {
ID                   uuid.UUID `json:"id"`
DayID                uuid.UUID `json:"day_id"`
ExerciseName         string    `json:"exercise_name"`
DurationMinutes      int32     `json:"duration_minutes"`
Description          string    `json:"description"`
CaloriesBurnEstimate int32     `json:"calories_burn_estimate"`
CreatedAt            time.Time `json:"created_at"`
}

type DayPrescribedMedication struct {
ID           uuid.UUID  `json:"id"`
DayID        uuid.UUID  `json:"day_id"`
MedicationID uuid.UUID  `json:"medication_id"`
Dosage       string     `json:"dosage"`
Frequency    string     `json:"frequency"`
Times        []string   `json:"times"`
Instructions string     `json:"instructions"`
StartDate    *time.Time `json:"start_date"`
EndDate      *time.Time `json:"end_date"`
CreatedAt    time.Time  `json:"created_at"`
}

type User struct {
ID             uuid.UUID      `json:"id"`
Role           string         `json:"role"`
Mobile         string         `json:"mobile"`
Email          *string        `json:"email"`
PasswordHash   *string        `json:"password_hash"`
FirstName      string         `json:"first_name"`
LastName       string         `json:"last_name"`
Gender         *string        `json:"gender"`
BirthDate      pgtype.Date    `json:"birth_date"`
Height         pgtype.Numeric `json:"height"`
Weight         pgtype.Numeric `json:"weight"`
AvatarUrl      *string        `json:"avatar_url"`
IsActive       bool           `json:"is_active"`
NutritionistID pgtype.UUID    `json:"nutritionist_id"`
CreatedAt      time.Time      `json:"created_at"`
UpdatedAt      time.Time      `json:"updated_at"`
}

// FoodLog represents a food log entry.
type FoodLog struct {
ID         uuid.UUID      `db:"id"`
ClientID   uuid.UUID      `db:"client_id"`
LocalID    string         `db:"local_id"`
LoggedAt   time.Time      `db:"logged_at"`
LoggedDate time.Time      `db:"logged_date"`
FoodID     *uuid.UUID     `db:"food_id"`
FoodName   string         `db:"food_name"`
Quantity   pgtype.Numeric `db:"quantity"`
Unit       string         `db:"unit"`
Calories   pgtype.Numeric `db:"calories"`
Protein    pgtype.Numeric `db:"protein"`
Carbs      pgtype.Numeric `db:"carbs"`
Fat        pgtype.Numeric `db:"fat"`
Notes      string         `db:"notes"`
CreatedAt  time.Time      `db:"created_at"`
}

// WaterLog represents a water intake log.
type WaterLog struct {
ID         uuid.UUID `db:"id"`
ClientID   uuid.UUID `db:"client_id"`
LocalID    string    `db:"local_id"`
LoggedAt   time.Time `db:"logged_at"`
LoggedDate time.Time `db:"logged_date"`
AmountMl   int32     `db:"amount_ml"`
Notes      string    `db:"notes"`
CreatedAt  time.Time `db:"created_at"`
}

// SleepLog represents a sleep record.
type SleepLog struct {
ID              uuid.UUID `db:"id"`
ClientID        uuid.UUID `db:"client_id"`
LocalID         string    `db:"local_id"`
LoggedDate      time.Time `db:"logged_date"`
SleepStart      time.Time `db:"sleep_start"`
SleepEnd        time.Time `db:"sleep_end"`
DurationMinutes int32     `db:"duration_minutes"`
Quality         int32     `db:"quality"`
Notes           string    `db:"notes"`
CreatedAt       time.Time `db:"created_at"`
}

// ExerciseLog represents an exercise session log.
type ExerciseLog struct {
ID              uuid.UUID `db:"id"`
ClientID        uuid.UUID `db:"client_id"`
LocalID         string    `db:"local_id"`
LoggedAt        time.Time `db:"logged_at"`
LoggedDate      time.Time `db:"logged_date"`
ExerciseName    string    `db:"exercise_name"`
DurationMinutes int32     `db:"duration_minutes"`
CaloriesBurned  int32     `db:"calories_burned"`
Notes           string    `db:"notes"`
CreatedAt       time.Time `db:"created_at"`
}

// MedicationLog represents a medication intake log.
type MedicationLog struct {
ID             uuid.UUID  `db:"id"`
ClientID       uuid.UUID  `db:"client_id"`
LocalID        string     `db:"local_id"`
LoggedAt       time.Time  `db:"logged_at"`
LoggedDate     time.Time  `db:"logged_date"`
MedicationID   *uuid.UUID `db:"medication_id"`
MedicationName string     `db:"medication_name"`
Dosage         string     `db:"dosage"`
Notes          string     `db:"notes"`
CreatedAt      time.Time  `db:"created_at"`
}

// BodyMeasurement represents a body measurement record.
type BodyMeasurement struct {
ID           uuid.UUID       `db:"id"`
ClientID     uuid.UUID       `db:"client_id"`
LocalID      string          `db:"local_id"`
MeasuredAt   time.Time       `db:"measured_at"`
MeasuredDate time.Time       `db:"measured_date"`
WeightKg     *pgtype.Numeric `db:"weight_kg"`
HeightCm     *pgtype.Numeric `db:"height_cm"`
WaistCm      *pgtype.Numeric `db:"waist_cm"`
HipCm        *pgtype.Numeric `db:"hip_cm"`
ChestCm      *pgtype.Numeric `db:"chest_cm"`
ArmCm        *pgtype.Numeric `db:"arm_cm"`
Notes        string          `db:"notes"`
CreatedAt    time.Time       `db:"created_at"`
}

// LabResult represents a lab result file upload.
type LabResult struct {
	ID             uuid.UUID `db:"id"`
	ClientID       uuid.UUID `db:"client_id"`
	NutritionistID uuid.UUID `db:"nutritionist_id"`
	FilePath       string    `db:"file_path"`
	OriginalName   string    `db:"original_name"`
	FileType       string    `db:"file_type"`
	FileSize       int64     `db:"file_size"`
	Notes          string    `db:"notes"`
	CreatedAt      time.Time `db:"created_at"`
}