// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countClientsByNutritionist = `-- name: CountClientsByNutritionist :one
SELECT COUNT(*) FROM users
WHERE nutritionist_id = $1 AND role = 'client'
`

func (q *Queries) CountClientsByNutritionist(ctx context.Context, nutritionistID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countClientsByNutritionist, nutritionistID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countNutritionists = `-- name: CountNutritionists :one
SELECT COUNT(*) FROM users WHERE role = 'nutritionist'
`

func (q *Queries) CountNutritionists(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countNutritionists)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    role, mobile, email, password_hash,
    first_name, last_name, gender, birth_date,
    height, weight, avatar_url, is_active, nutritionist_id
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10, $11, $12, $13
) RETURNING id, role, mobile, email, password_hash, first_name, last_name, gender, birth_date, height, weight, avatar_url, is_active, nutritionist_id, created_at, updated_at
`

type CreateUserParams struct {
	Role           string         `json:"role"`
	Mobile         string         `json:"mobile"`
	Email          *string        `json:"email"`
	PasswordHash   *string        `json:"password_hash"`
	FirstName      string         `json:"first_name"`
	LastName       string         `json:"last_name"`
	Gender         *string        `json:"gender"`
	BirthDate      pgtype.Date    `json:"birth_date"`
	Height         pgtype.Numeric `json:"height"`
	Weight         pgtype.Numeric `json:"weight"`
	AvatarUrl      *string        `json:"avatar_url"`
	IsActive       bool           `json:"is_active"`
	NutritionistID pgtype.UUID    `json:"nutritionist_id"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Role,
		arg.Mobile,
		arg.Email,
		arg.PasswordHash,
		arg.FirstName,
		arg.LastName,
		arg.Gender,
		arg.BirthDate,
		arg.Height,
		arg.Weight,
		arg.AvatarUrl,
		arg.IsActive,
		arg.NutritionistID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Mobile,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Gender,
		&i.BirthDate,
		&i.Height,
		&i.Weight,
		&i.AvatarUrl,
		&i.IsActive,
		&i.NutritionistID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const existsByEmail = `-- name: ExistsByEmail :one
SELECT EXISTS(SELECT 1 FROM users WHERE email = $1)::boolean
`

func (q *Queries) ExistsByEmail(ctx context.Context, email *string) (bool, error) {
	row := q.db.QueryRow(ctx, existsByEmail, email)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const existsByMobile = `-- name: ExistsByMobile :one
SELECT EXISTS(SELECT 1 FROM users WHERE mobile = $1)::boolean
`

func (q *Queries) ExistsByMobile(ctx context.Context, mobile string) (bool, error) {
	row := q.db.QueryRow(ctx, existsByMobile, mobile)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, role, mobile, email, password_hash, first_name, last_name, gender, birth_date, height, weight, avatar_url, is_active, nutritionist_id, created_at, updated_at FROM users WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Mobile,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Gender,
		&i.BirthDate,
		&i.Height,
		&i.Weight,
		&i.AvatarUrl,
		&i.IsActive,
		&i.NutritionistID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, role, mobile, email, password_hash, first_name, last_name, gender, birth_date, height, weight, avatar_url, is_active, nutritionist_id, created_at, updated_at FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Mobile,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Gender,
		&i.BirthDate,
		&i.Height,
		&i.Weight,
		&i.AvatarUrl,
		&i.IsActive,
		&i.NutritionistID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByMobile = `-- name: GetUserByMobile :one
SELECT id, role, mobile, email, password_hash, first_name, last_name, gender, birth_date, height, weight, avatar_url, is_active, nutritionist_id, created_at, updated_at FROM users WHERE mobile = $1 LIMIT 1
`

func (q *Queries) GetUserByMobile(ctx context.Context, mobile string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByMobile, mobile)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Mobile,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Gender,
		&i.BirthDate,
		&i.Height,
		&i.Weight,
		&i.AvatarUrl,
		&i.IsActive,
		&i.NutritionistID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listClientsByNutritionist = `-- name: ListClientsByNutritionist :many
SELECT id, role, mobile, email, password_hash, first_name, last_name, gender, birth_date, height, weight, avatar_url, is_active, nutritionist_id, created_at, updated_at FROM users
WHERE nutritionist_id = $1 AND role = 'client'
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListClientsByNutritionistParams struct {
	NutritionistID pgtype.UUID `json:"nutritionist_id"`
	Limit          int32       `json:"limit"`
	Offset         int32       `json:"offset"`
}

func (q *Queries) ListClientsByNutritionist(ctx context.Context, arg ListClientsByNutritionistParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listClientsByNutritionist, arg.NutritionistID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.Mobile,
			&i.Email,
			&i.PasswordHash,
			&i.FirstName,
			&i.LastName,
			&i.Gender,
			&i.BirthDate,
			&i.Height,
			&i.Weight,
			&i.AvatarUrl,
			&i.IsActive,
			&i.NutritionistID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNutritionists = `-- name: ListNutritionists :many
SELECT id, role, mobile, email, password_hash, first_name, last_name, gender, birth_date, height, weight, avatar_url, is_active, nutritionist_id, created_at, updated_at FROM users
WHERE role = 'nutritionist'
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListNutritionistsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListNutritionists(ctx context.Context, arg ListNutritionistsParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listNutritionists, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.Mobile,
			&i.Email,
			&i.PasswordHash,
			&i.FirstName,
			&i.LastName,
			&i.Gender,
			&i.BirthDate,
			&i.Height,
			&i.Weight,
			&i.AvatarUrl,
			&i.IsActive,
			&i.NutritionistID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
    first_name      = $2,
    last_name       = $3,
    gender          = $4,
    birth_date      = $5,
    height          = $6,
    weight          = $7,
    avatar_url      = $8,
    is_active       = $9,
    password_hash   = $10,
    updated_at      = NOW()
WHERE id = $1
RETURNING id, role, mobile, email, password_hash, first_name, last_name, gender, birth_date, height, weight, avatar_url, is_active, nutritionist_id, created_at, updated_at
`

type UpdateUserParams struct {
	ID           uuid.UUID      `json:"id"`
	FirstName    string         `json:"first_name"`
	LastName     string         `json:"last_name"`
	Gender       *string        `json:"gender"`
	BirthDate    pgtype.Date    `json:"birth_date"`
	Height       pgtype.Numeric `json:"height"`
	Weight       pgtype.Numeric `json:"weight"`
	AvatarUrl    *string        `json:"avatar_url"`
	IsActive     bool           `json:"is_active"`
	PasswordHash *string        `json:"password_hash"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Gender,
		arg.BirthDate,
		arg.Height,
		arg.Weight,
		arg.AvatarUrl,
		arg.IsActive,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Mobile,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Gender,
		&i.BirthDate,
		&i.Height,
		&i.Weight,
		&i.AvatarUrl,
		&i.IsActive,
		&i.NutritionistID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
